// packages/components-react/src/table/Table.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface TableColumn<T = unknown> {
  key: string
  header: ReactNode
  render?: (row: T) => ReactNode
}

export interface TableProps<T = unknown> {
  columns: TableColumn<T>[]
  rows: T[]
  getRowId?: (row: T, index: number) => string
  caption?: string
  className?: string
}

export function Table<T>({ columns, rows, getRowId, caption, className }: TableProps<T>) {
  const classes = ['cu-table', className].filter(Boolean).join(' ')

  return (
    <div className={classes} data-ai-role="table" data-ai-intent="inspect-tabular-data" data-ai-state={rows.length === 0 ? 'empty' : 'default'}>
      <table className="cu-table__table">
        {caption ? <caption className="cu-table__caption">{caption}</caption> : null}
        <thead className="cu-table__head">
          <tr>
            {columns.map((column) => (
              <th key={column.key} className="cu-table__header" scope="col">
                {column.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="cu-table__body">
          {rows.map((row, index) => (
            <tr key={getRowId ? getRowId(row, index) : index} className="cu-table__row">
              {columns.map((column) => (
                <td key={column.key} className="cu-table__cell">
                  {column.render ? column.render(row) : String((row as Record<string, ReactNode>)[column.key])}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// packages/components-vue/src/table/Table.vue
<script lang="ts">
export interface TableColumn {
  key: string
  header: string
}

export interface TableProps {
  columns: TableColumn[]
  rows: Record<string, unknown>[]
  caption?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<TableProps>()

const classes = computed(() => ['cu-table', props.class].filter(Boolean).join(' '))
const dataAiState = computed(() => (props.rows.length === 0 ? 'empty' : 'default'))

function cellValue(row: Record<string, unknown>, key: string) {
  const value = row[key]
  return value == null ? '' : String(value)
}
</script>

<template>
  <div :class="classes" data-ai-role="table" data-ai-intent="inspect-tabular-data" :data-ai-state="dataAiState">
    <table class="cu-table__table">
      <caption v-if="caption" class="cu-table__caption">{{ caption }}</caption>
      <thead class="cu-table__head">
        <tr>
          <th v-for="column in columns" :key="column.key" class="cu-table__header" scope="col">
            {{ column.header }}
          </th>
        </tr>
      </thead>
      <tbody class="cu-table__body">
        <tr v-for="(row, index) in rows" :key="index" class="cu-table__row">
          <td v-for="column in columns" :key="column.key" class="cu-table__cell">
            {{ cellValue(row, column.key) }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped src="./styles.css"></style>
