// packages/components-vue/src/drawer/Drawer.vue
<script lang="ts">
export interface DrawerProps {
  triggerLabel: string
  title: string
  closeLabel: string
  position?: 'start' | 'end'
  open?: boolean
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { DialogPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<DrawerProps>(), { position: 'end' })
const emit = defineEmits<{ openChange: [open: boolean] }>()
const classes = computed(() => ['cu-drawer', 'cu-drawer--' + props.position, props.class].filter(Boolean).join(' '))

function onOpenChange(details: { open: boolean }) {
  emit('openChange', details.open)
}
</script>

<template>
  <DialogPrimitive.Root :open="open" @open-change="onOpenChange">
    <DialogPrimitive.Trigger class="cu-drawer__trigger">{{ triggerLabel }}</DialogPrimitive.Trigger>
    <Teleport to="body">
      <DialogPrimitive.Backdrop class="cu-drawer__backdrop" />
      <DialogPrimitive.Positioner>
        <DialogPrimitive.Content :class="classes" data-ai-role="drawer" data-ai-intent="reveal-detail" :data-ai-state="open ? 'open' : 'closed'">
          <DialogPrimitive.Title class="cu-drawer__title">{{ title }}</DialogPrimitive.Title>
          <div class="cu-drawer__body"><slot /></div>
          <DialogPrimitive.CloseTrigger class="cu-drawer__close">{{ closeLabel }}</DialogPrimitive.CloseTrigger>
        </DialogPrimitive.Content>
      </DialogPrimitive.Positioner>
    </Teleport>
  </DialogPrimitive.Root>
</template>

<style src="./styles.css"></style>

// packages/components-react/src/drawer/Drawer.tsx
import { DialogPrimitive } from '@chameleon-ui/primitives'
import type { ReactNode } from 'react'
import './styles.css'

export interface DrawerProps {
  triggerLabel: string
  title: string
  closeLabel: string
  children?: ReactNode
  position?: 'start' | 'end'
  open?: boolean
  onOpenChange?: (open: boolean) => void
  className?: string
}

export function Drawer({ triggerLabel, title, closeLabel, children, position = 'end', open, onOpenChange, className }: DrawerProps) {
  const classes = ['cu-drawer', 'cu-drawer--' + position, className].filter(Boolean).join(' ')
  return (
    <DialogPrimitive.Root
      open={open}
      onOpenChange={(details) => onOpenChange?.(details.open)}
    >
      <DialogPrimitive.Trigger className="cu-drawer__trigger">{triggerLabel}</DialogPrimitive.Trigger>
      <DialogPrimitive.Portal>
        <DialogPrimitive.Backdrop className="cu-drawer__backdrop" />
        <DialogPrimitive.Positioner>
          <DialogPrimitive.Content className={classes} data-ai-role="drawer" data-ai-intent="reveal-detail" data-ai-state={open ? 'open' : 'closed'}>
            <DialogPrimitive.Title className="cu-drawer__title">{title}</DialogPrimitive.Title>
            <div className="cu-drawer__body">{children}</div>
            <DialogPrimitive.CloseTrigger className="cu-drawer__close">{closeLabel}</DialogPrimitive.CloseTrigger>
          </DialogPrimitive.Content>
        </DialogPrimitive.Positioner>
      </DialogPrimitive.Portal>
    </DialogPrimitive.Root>
  )
}
