// chameleon-ui/packages/components-vue/src/container/Container.vue
<script lang="ts">
export type ContainerSize = 'sm' | 'md' | 'lg'

export interface ContainerProps {
  size?: ContainerSize
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<ContainerProps>(), {
  size: 'md'
})
const classes = computed(() => ["cu-container", 'cu-container--' + props.size, props.class].filter(Boolean).join(' '))
</script>

<template>
  <div :class="classes" data-ai-role="container" data-ai-intent="group-content" :data-ai-state="size">
    <div class="cu-container__body"><slot /></div>
  </div>
</template>

<style scoped src="./styles.css"></style>

// packages/components/src/container/Container.tsx
import type { ReactNode } from 'react'
import './styles.css'

export type ContainerSize = 'sm' | 'md' | 'lg'

export interface ContainerProps {
  children: ReactNode
  size?: ContainerSize
  className?: string
}

export function Container({ children, size = 'md', className }: ContainerProps) {
  const classes = ['cu-container', 'cu-container--' + size, className].filter(Boolean).join(' ')
  return (
    <div
      className={classes}
      data-ai-role="container"
      data-ai-intent="group-content"
      data-ai-state={size}
    >
      <div className="cu-container__body">{children}</div>
    </div>
  )
}
