// chameleon-ui/packages/components-vue/src/typography/Typography.vue
<script lang="ts">
export type TypographyVariant = 'heading-1' | 'heading-2' | 'body' | 'caption'
export type TypographyTag = 'h1' | 'h2' | 'h3' | 'p' | 'span' | 'div'

export interface TypographyProps {
  variant?: TypographyVariant
  as?: TypographyTag
  class?: string
}

export const defaultElement: Record<TypographyVariant, TypographyTag> = {
  'heading-1': 'h1',
  'heading-2': 'h2',
  body: 'p',
  caption: 'span',
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<TypographyProps>(), {
  variant: 'body',
})

const tag = computed(() => props.as ?? defaultElement[props.variant])
const classes = computed(() =>
  ['cu-typography', `cu-typography--${props.variant}`, props.class].filter(Boolean).join(' '),
)
</script>

<template>
  <component
    :is="tag"
    :class="classes"
    data-ai-role="typography"
    data-ai-intent="style-text"
    :data-ai-state="variant"
    :data-variant="variant"
  >
    <slot />
  </component>
</template>

<style src="./styles.css"></style>

// packages/components-react/src/typography/Typography.tsx
import type { ReactNode } from 'react'
import './styles.css'

export type TypographyVariant = 'heading-1' | 'heading-2' | 'body' | 'caption'

export interface TypographyProps {
  variant?: TypographyVariant
  /** Semantic element to render; defaults from the variant if omitted. */
  as?: 'h1' | 'h2' | 'h3' | 'p' | 'span' | 'div'
  children: ReactNode
  className?: string
}

const defaultElement: Record<TypographyVariant, 'h1' | 'h2' | 'p' | 'span'> = {
  'heading-1': 'h1',
  'heading-2': 'h2',
  body: 'p',
  caption: 'span',
}

export function Typography({ variant = 'body', as, children, className }: TypographyProps) {
  const Element = as ?? defaultElement[variant]
  const classes = ['cu-typography', `cu-typography--${variant}`, className].filter(Boolean).join(' ')

  return (
    <Element className={classes} data-ai-role="typography" data-ai-intent="style-text" data-ai-state={variant} data-variant={variant}>
      {children}
    </Element>
  )
}
