// packages/components-vue/src/chip/Chip.vue
<script lang="ts">
export interface ChipProps {
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger'
  class?: string
}
</script>

<script setup lang="ts">
import { computed, getCurrentInstance } from 'vue'

const props = withDefaults(defineProps<ChipProps>(), {
  variant: 'default'
})
const emit = defineEmits<{ remove: [] }>()
const instance = getCurrentInstance()
const hasRemove = computed(() => typeof instance?.vnode.props?.onRemove === 'function')
const classes = computed(() => ["cu-chip", 'cu-chip--' + props.variant, props.class].filter(Boolean).join(' '))
</script>

<template>
  <span :class="classes" data-ai-role="chip" data-ai-intent="filter-selection" :data-ai-state="hasRemove ? 'removable' : 'default'">
    <slot />
    <button v-if="hasRemove" class="cu-chip__remove" type="button" aria-label="Remove" @click="emit('remove')">×</button>
  </span>
</template>

<style scoped src="./styles.css"></style>

// chameleon-ui/packages/components/src/chip/Chip.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface ChipProps {
  children: ReactNode
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger'
  onRemove?: () => void
  className?: string
}

export function Chip({ children, variant = 'default', onRemove, className }: ChipProps) {
  const classes = ['cu-chip', 'cu-chip--' + variant, className].filter(Boolean).join(' ')
  return (
    <span className={classes} data-ai-role="chip" data-ai-intent="filter-selection" data-ai-state={onRemove ? 'removable' : 'default'}>
      {children}
      {onRemove ? (
        <button className="cu-chip__remove" onClick={onRemove} type="button" aria-label="Remove">×</button>
      ) : null}
    </span>
  )
}
