// packages/components-vue/src/progress/Progress.vue
<script lang="ts">
export interface ProgressProps {
  value: number
  max?: number
  size?: 'sm' | 'md'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<ProgressProps>(), {
  max: 100,
  size: 'md',
})

const classes = computed(() =>
  ['cu-progress', `cu-progress--${props.size}`, props.class].filter(Boolean).join(' '),
)
</script>

<template>
  <progress :class="classes" data-ai-role="progress" data-ai-state="default" data-ai-intent="show-progress" :max="max" :value="value">
    {{ value }}%
  </progress>
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/progress/Progress.tsx
import './styles.css'

export interface ProgressProps {
  value: number
  max?: number
  size?: 'sm' | 'md'
  className?: string
}

export function Progress({ value, max = 100, size = 'md', className }: ProgressProps) {
  const classes = ['cu-progress', 'cu-progress--' + size, className].filter(Boolean).join(' ')
  return (
    <progress
      className={classes}
      data-ai-role="progress" data-ai-state="default" data-ai-intent="show-progress"
      max={max}
      value={value}
    >
      {value}%
    </progress>
  )
}
