// chameleon-ui/packages/components-vue/src/skeleton/Skeleton.vue
<script lang="ts">
export interface SkeletonProps {
  variant?: 'text' | 'circle' | 'rectangle'
  width?: string
  height?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<SkeletonProps>(), {
  variant: 'text',
  width: '100%',
  height: '1rem'
})
const classes = computed(() => ["cu-skeleton", 'cu-skeleton--' + props.variant, props.class].filter(Boolean).join(' '))
const style = computed(() => ({ width: props.width, height: props.height }))
</script>

<template>
  <div aria-hidden="true" :class="classes" data-ai-role="skeleton" data-ai-intent="indicate-loading" data-ai-state="loading" :style="style" />
</template>

<style scoped src="./styles.css"></style>

// chameleon-ui/packages/components/src/skeleton/Skeleton.tsx
import './styles.css'

export interface SkeletonProps {
  variant?: 'text' | 'circle' | 'rectangle'
  width?: string
  height?: string
  className?: string
}

export function Skeleton({ variant = 'text', width = '100%', height = '1rem', className }: SkeletonProps) {
  const classes = ['cu-skeleton', 'cu-skeleton--' + variant, className].filter(Boolean).join(' ')
  const style = { width, height }
  return <div aria-hidden="true" className={classes} data-ai-role="skeleton" data-ai-intent="indicate-loading" data-ai-state="loading" style={style} />
}
