// packages/components-react/src/graph-view/GraphView.tsx
import './styles.css'

export interface GraphNode {
  id: string
  label: string
}

export interface GraphLink {
  source: string
  target: string
}

export interface GraphViewProps {
  nodes: GraphNode[]
  links: GraphLink[]
  label: string
  className?: string
}

const SIZE = 320
const CENTER = SIZE / 2
const RADIUS = 120

/**
 * @complexity time O(n + m) | space O(n) | n = nodes, m = links; ring layout places node i at a fixed angle
 * @guarantees deterministic positions with no simulation; large graphs must paginate or filter upstream
 */
export function GraphView({ nodes, links, label, className }: GraphViewProps) {
  const classes = ['cu-graph-view', className].filter(Boolean).join(' ')
  const positions = new Map<string, { x: number; y: number }>()
  nodes.forEach((node, index) => {
    const angle = (2 * Math.PI * index) / Math.max(1, nodes.length) - Math.PI / 2
    positions.set(node.id, { x: CENTER + RADIUS * Math.cos(angle), y: CENTER + RADIUS * Math.sin(angle) })
  })

  return (
    <div className={classes} data-ai-role="graph-view" data-ai-intent="enumerate-items" data-ai-state={nodes.length === 0 ? 'empty' : 'default'}>
      <svg className="cu-graph-view__svg" viewBox={`0 0 ${SIZE} ${SIZE}`} role="img" aria-label={label}>
        {links.map((link, index) => {
          const from = positions.get(link.source)
          const to = positions.get(link.target)
          if (!from || !to) return null
          return <line key={index} className="cu-graph-view__link" x1={from.x} y1={from.y} x2={to.x} y2={to.y} />
        })}
        {nodes.map((node) => {
          const position = positions.get(node.id)
          if (!position) return null
          return (
            <g key={node.id} className="cu-graph-view__node">
              <circle cx={position.x} cy={position.y} r={16} />
              <text x={position.x} y={position.y + 32} textAnchor="middle" className="cu-graph-view__label">
                {node.label}
              </text>
            </g>
          )
        })}
      </svg>
      <ul className="cu-graph-view__list">
        {nodes.map((node) => (
          <li key={node.id}>{node.label}</li>
        ))}
      </ul>
    </div>
  )
}

// packages/components-vue/src/graph-view/GraphView.vue
<script lang="ts">
export interface GraphNode {
  id: string
  label: string
}

export interface GraphLink {
  source: string
  target: string
}

export interface GraphViewProps {
  nodes: GraphNode[]
  links: GraphLink[]
  label: string
  class?: string
}

const SIZE = 320
const CENTER = SIZE / 2
const RADIUS = 120
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<GraphViewProps>()
const classes = computed(() => ['cu-graph-view', props.class].filter(Boolean).join(' '))
const positions = computed(() => {
  const map = new Map<string, { x: number; y: number }>()
  props.nodes.forEach((node, index) => {
    const angle = (2 * Math.PI * index) / Math.max(1, props.nodes.length) - Math.PI / 2
    map.set(node.id, { x: CENTER + RADIUS * Math.cos(angle), y: CENTER + RADIUS * Math.sin(angle) })
  })
  return map
})
const paintedLinks = computed(() =>
  props.links
    .map((link) => ({ from: positions.value.get(link.source), to: positions.value.get(link.target) }))
    .filter((link): link is { from: { x: number; y: number }; to: { x: number; y: number } } => Boolean(link.from && link.to)),
)
</script>

<template>
  <div :class="classes" data-ai-role="graph-view" data-ai-intent="enumerate-items" :data-ai-state="nodes.length === 0 ? 'empty' : 'default'">
    <svg class="cu-graph-view__svg" :viewBox="'0 0 ' + SIZE + ' ' + SIZE" role="img" :aria-label="label">
      <line v-for="(link, index) in paintedLinks" :key="index" class="cu-graph-view__link" :x1="link.from.x" :y1="link.from.y" :x2="link.to.x" :y2="link.to.y" />
      <g v-for="node in nodes" :key="node.id" class="cu-graph-view__node">
        <circle v-if="positions.get(node.id)" :cx="positions.get(node.id)!.x" :cy="positions.get(node.id)!.y" r="16" />
        <text v-if="positions.get(node.id)" :x="positions.get(node.id)!.x" :y="positions.get(node.id)!.y + 32" text-anchor="middle" class="cu-graph-view__label">{{ node.label }}</text>
      </g>
    </svg>
    <ul class="cu-graph-view__list">
      <li v-for="node in nodes" :key="node.id">{{ node.label }}</li>
    </ul>
  </div>
</template>

<style scoped src="./styles.css"></style>
