// chameleon-ui/packages/components-vue/src/switch/Switch.vue
<script lang="ts">
export interface SwitchProps {
  disabled?: boolean
  label: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { SwitchPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<SwitchProps>(), {
  disabled: false,
})

const checked = defineModel<boolean>('modelValue', { default: false })

const classes = computed(() => ['cu-switch', props.class].filter(Boolean).join(' '))
const dataAiState = computed(() =>
  checked.value ? 'checked' : props.disabled ? 'disabled' : 'default',
)

function onCheckedChange(details: { checked: boolean }) {
  checked.value = !!details.checked
}
</script>

<template>
  <SwitchPrimitive.Root
    :checked="checked"
    :class="classes"
    data-ai-role="switch"
    data-ai-intent="toggle-setting"
    :data-ai-state="dataAiState"
    :disabled="disabled"
    @checked-change="onCheckedChange"
  >
    <SwitchPrimitive.Label class="cu-switch__label">{{ label }}</SwitchPrimitive.Label>
    <SwitchPrimitive.Control class="cu-switch__control">
      <SwitchPrimitive.Thumb class="cu-switch__thumb" />
    </SwitchPrimitive.Control>
    <SwitchPrimitive.HiddenInput />
  </SwitchPrimitive.Root>
</template>

<style scoped src="./styles.css"></style>

// chameleon-ui/packages/components/src/switch/Switch.tsx
import { SwitchPrimitive } from '@chameleon-ui/primitives'
import './styles.css'

export interface SwitchProps {
  checked: boolean
  onChange: (checked: boolean) => void
  label: string
  disabled?: boolean
  className?: string
}

export function Switch({ checked, onChange, label, disabled = false, className }: SwitchProps) {
  const classes = ['cu-switch', className].filter(Boolean).join(' ')

  return (
    <SwitchPrimitive.Root
      checked={checked}
      className={classes}
      data-ai-role="switch" data-ai-intent="toggle-setting"
      data-ai-state={checked ? 'checked' : disabled ? 'disabled' : 'default'}
      disabled={disabled}
      onCheckedChange={(details) => onChange(!!details.checked)}
    >
      <SwitchPrimitive.Label className="cu-switch__label">{label}</SwitchPrimitive.Label>
      <SwitchPrimitive.Control className="cu-switch__control">
        <SwitchPrimitive.Thumb className="cu-switch__thumb" />
      </SwitchPrimitive.Control>
      <SwitchPrimitive.HiddenInput />
    </SwitchPrimitive.Root>
  )
}
