// chameleon-ui/packages/components-vue/src/app-shell/AppShell.vue
<script lang="ts">
export interface AppShellProps {
  sidebarLabel?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed, useSlots } from 'vue'

const props = withDefaults(defineProps<AppShellProps>(), {
  sidebarLabel: 'Sidebar',
})

const slots = useSlots()
const classes = computed(() => ['cu-app-shell', props.class].filter(Boolean).join(' '))
</script>

<template>
  <div :class="classes" data-ai-role="app-shell" data-ai-intent="layout-shell" data-ai-state="default">
    <div class="cu-app-shell__frame">
      <header class="cu-app-shell__header">
        <slot name="header" />
      </header>
      <div v-if="slots.navigation" class="cu-app-shell__nav">
        <slot name="navigation" />
      </div>
      <aside v-if="slots.sidebar" :aria-label="sidebarLabel" class="cu-app-shell__sidebar">
        <slot name="sidebar" />
      </aside>
      <main class="cu-app-shell__main">
        <slot />
      </main>
      <div v-if="slots.tabBar" class="cu-app-shell__tab-bar">
        <slot name="tabBar" />
      </div>
    </div>
  </div>
</template>

<style src="./styles.css"></style>

// packages/components/src/app-shell/AppShell.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface AppShellProps {
  header: ReactNode
  sidebar: ReactNode
  children: ReactNode
  /** Compact/tablet Navigation morph. Hidden by container query at desktop (80rem). */
  tabBar?: ReactNode
  sidebarLabel?: string
  className?: string
}

export function AppShell({
  header,
  sidebar,
  children,
  tabBar,
  sidebarLabel = 'Sidebar',
  className,
}: AppShellProps) {
  const classes = ['cu-app-shell', className].filter(Boolean).join(' ')

  return (
    <div className={classes} data-ai-role="app-shell" data-ai-intent="layout-shell" data-ai-state="default">
      <div className="cu-app-shell__frame">
        <header className="cu-app-shell__header">{header}</header>
        <aside aria-label={sidebarLabel} className="cu-app-shell__sidebar">
          {sidebar}
        </aside>
        <main className="cu-app-shell__main">{children}</main>
        {tabBar ? <div className="cu-app-shell__tab-bar">{tabBar}</div> : null}
      </div>
    </div>
  )
}
