// packages/components-vue/src/steps/Steps.vue
<script lang="ts">
export interface StepItem {
  value: string
  label: string
  description?: string
}

export type StepsStatus = 'start' | 'in-progress' | 'complete'

export interface StepsProps {
  items: StepItem[]
  currentValue: string
  label: string
  class?: string
}

function statusFor(currentIndex: number, lastIndex: number): StepsStatus {
  if (currentIndex <= 0) return 'start'
  if (currentIndex >= lastIndex) return 'complete'
  return 'in-progress'
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<StepsProps>()
const emit = defineEmits<{ select: [value: string] }>()
const classes = computed(() => ['cu-steps', props.class].filter(Boolean).join(' '))
const currentIndex = computed(() => props.items.findIndex((item) => item.value === props.currentValue))
const state = computed(() => statusFor(currentIndex.value, Math.max(0, props.items.length - 1)))
const selectable = computed(() => typeof getListener() === 'function')

function getListener() {
  return undefined
}

function itemStatus(index: number) {
  if (index < currentIndex.value) return 'complete'
  if (index === currentIndex.value) return 'current'
  return 'upcoming'
}
</script>

<template>
  <nav :class="classes" :aria-label="label" data-ai-role="steps" data-ai-intent="enumerate-items" :data-ai-state="state">
    <ol class="cu-steps__list">
      <li v-for="(item, index) in items" :key="item.value" :class="'cu-steps__item cu-steps__item--' + itemStatus(index)" :data-status="itemStatus(index)">
        <button
          v-if="$attrs.onSelect"
          type="button"
          class="cu-steps__button"
          :aria-current="itemStatus(index) === 'current' ? 'step' : undefined"
          @click="emit('select', item.value)"
        >
          <span class="cu-steps__index" aria-hidden="true">{{ index + 1 }}</span>
          <span class="cu-steps__copy">
            <span class="cu-steps__label">{{ item.label }}</span>
            <span v-if="item.description" class="cu-steps__description">{{ item.description }}</span>
          </span>
        </button>
        <div v-else class="cu-steps__static" :aria-current="itemStatus(index) === 'current' ? 'step' : undefined">
          <span class="cu-steps__index" aria-hidden="true">{{ index + 1 }}</span>
          <span class="cu-steps__copy">
            <span class="cu-steps__label">{{ item.label }}</span>
            <span v-if="item.description" class="cu-steps__description">{{ item.description }}</span>
          </span>
        </div>
      </li>
    </ol>
  </nav>
</template>

<style scoped src="./styles.css"></style>

// chameleon-ui/packages/components/src/steps/Steps.tsx
import './styles.css'

export interface StepItem {
  value: string
  label: string
  description?: string
}

export type StepsStatus = 'start' | 'in-progress' | 'complete'

function statusFor(currentIndex: number, lastIndex: number): StepsStatus {
  if (currentIndex <= 0) return 'start'
  if (currentIndex >= lastIndex) return 'complete'
  return 'in-progress'
}

export interface StepsProps {
  items: StepItem[]
  currentValue: string
  onSelect?: (value: string) => void
  label: string
  className?: string
}

export function Steps({ items, currentValue, onSelect, label, className }: StepsProps) {
  const classes = ['cu-steps', className].filter(Boolean).join(' ')
  const currentIndex = items.findIndex((item) => item.value === currentValue)
  const state = statusFor(currentIndex, Math.max(0, items.length - 1))

  return (
    <nav className={classes} aria-label={label} data-ai-role="steps" data-ai-intent="enumerate-items" data-ai-state={state}>
      <ol className="cu-steps__list">
        {items.map((item, index) => {
          const status = index < currentIndex ? 'complete' : index === currentIndex ? 'current' : 'upcoming'
          const content = (
            <>
              <span className="cu-steps__index" aria-hidden="true">
                {index + 1}
              </span>
              <span className="cu-steps__copy">
                <span className="cu-steps__label">{item.label}</span>
                {item.description ? <span className="cu-steps__description">{item.description}</span> : null}
              </span>
            </>
          )
          return (
            <li key={item.value} className={'cu-steps__item cu-steps__item--' + status} data-status={status}>
              {onSelect ? (
                <button
                  type="button"
                  className="cu-steps__button"
                  aria-current={status === 'current' ? 'step' : undefined}
                  onClick={() => onSelect(item.value)}
                >
                  {content}
                </button>
              ) : (
                <div className="cu-steps__static" aria-current={status === 'current' ? 'step' : undefined}>
                  {content}
                </div>
              )}
            </li>
          )
        })}
      </ol>
    </nav>
  )
}
