// packages/components-react/src/sidebar/Sidebar.tsx
import type { ReactNode } from 'react'
import { useId, useState } from 'react'
import './styles.css'

export interface SidebarItem {
  value: string
  label: ReactNode
}

export interface SidebarProps {
  /** Accessible name of the navigation landmark. */
  label: string
  items: SidebarItem[]
  header?: ReactNode
  activeValue?: string
  onSelect?: (value: string) => void
  /** Show the collapse toggle (tablet pattern). */
  collapsible?: boolean
  collapsed?: boolean
  defaultCollapsed?: boolean
  onCollapsedChange?: (collapsed: boolean) => void
  /** Toggle accessible name when collapsed. */
  expandLabel?: string
  /** Toggle accessible name when expanded. */
  collapseLabel?: string
  className?: string
}

export function Sidebar({
  label,
  items,
  header,
  activeValue,
  onSelect,
  collapsible = false,
  collapsed,
  defaultCollapsed = false,
  onCollapsedChange,
  expandLabel = 'Expand sidebar',
  collapseLabel = 'Collapse sidebar',
  className,
}: SidebarProps) {
  const [internalCollapsed, setInternalCollapsed] = useState(defaultCollapsed)
  const isCollapsed = collapsed ?? internalCollapsed
  const navId = useId()

  function requestCollapsedChange(next: boolean) {
    if (collapsed === undefined) setInternalCollapsed(next)
    onCollapsedChange?.(next)
  }

  const classes = [
    'cu-sidebar',
    isCollapsed && 'cu-sidebar--collapsed',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <aside
      className={classes}
      aria-label={label}
      data-ai-role="sidebar"
      data-ai-intent="navigate-sections"
      data-ai-state={isCollapsed ? 'collapsed' : 'expanded'}
    >
      {header ? <div className="cu-sidebar__header">{header}</div> : null}
      <nav id={navId} className="cu-sidebar__nav" aria-label={label}>
        <ul className="cu-sidebar__list">
          {items.map((item) => (
            <li key={item.value} className="cu-sidebar__entry">
              <button
                type="button"
                className="cu-sidebar__item"
                aria-current={activeValue === item.value ? 'page' : undefined}
                aria-label={typeof item.label === 'string' ? item.label : undefined}
                onClick={() => onSelect?.(item.value)}
              >
                <span className="cu-sidebar__label">{item.label}</span>
              </button>
            </li>
          ))}
        </ul>
      </nav>
      {collapsible ? (
        <button
          type="button"
          className="cu-sidebar__toggle"
          aria-expanded={!isCollapsed}
          aria-controls={navId}
          aria-label={isCollapsed ? expandLabel : collapseLabel}
          onClick={() => requestCollapsedChange(!isCollapsed)}
        >
          <span aria-hidden="true" className="cu-sidebar__toggle-icon" data-direction={isCollapsed ? 'expand' : 'collapse'}>
            <svg viewBox="0 0 24 24" className="cu-sidebar__toggle-svg">
              <path
                d={isCollapsed ? 'M9 6l6 6-6 6' : 'M15 6l-6 6 6 6'}
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
              />
            </svg>
          </span>
          <span className="cu-sidebar__label">{isCollapsed ? expandLabel : collapseLabel}</span>
        </button>
      ) : null}
    </aside>
  )
}

// chameleon-ui/packages/components-vue/src/sidebar/Sidebar.vue
<script lang="ts">
export interface SidebarItem {
  value: string
  label: string
}

export interface SidebarProps {
  label: string
  items: SidebarItem[]
  activeValue?: string
  collapsible?: boolean
  collapsed?: boolean
  defaultCollapsed?: boolean
  expandLabel?: string
  collapseLabel?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed, ref, useId, useSlots } from 'vue'

const props = withDefaults(defineProps<SidebarProps>(), {
  collapsible: false,
  defaultCollapsed: false,
  expandLabel: 'Expand sidebar',
  collapseLabel: 'Collapse sidebar',
})
const emit = defineEmits<{ select: [value: string]; collapsedChange: [collapsed: boolean] }>()
const slots = useSlots()
const internalCollapsed = ref(props.defaultCollapsed)
const isCollapsed = computed(() => props.collapsed ?? internalCollapsed.value)
const navId = useId()
const classes = computed(() => ['cu-sidebar', isCollapsed.value && 'cu-sidebar--collapsed', props.class].filter(Boolean).join(' '))

function requestCollapsedChange(next: boolean) {
  if (props.collapsed === undefined) internalCollapsed.value = next
  emit('collapsedChange', next)
}
</script>

<template>
  <aside :class="classes" :aria-label="label" data-ai-role="sidebar" data-ai-intent="navigate-sections" :data-ai-state="isCollapsed ? 'collapsed' : 'expanded'">
    <div v-if="slots.header" class="cu-sidebar__header"><slot name="header" /></div>
    <nav :id="navId" class="cu-sidebar__nav" :aria-label="label">
      <ul class="cu-sidebar__list">
        <li v-for="item in items" :key="item.value" class="cu-sidebar__entry">
          <button
            type="button"
            class="cu-sidebar__item"
            :aria-current="activeValue === item.value ? 'page' : undefined"
            :aria-label="item.label"
            @click="emit('select', item.value)"
          >
            <span class="cu-sidebar__label">{{ item.label }}</span>
          </button>
        </li>
      </ul>
    </nav>
    <button
      v-if="collapsible"
      type="button"
      class="cu-sidebar__toggle"
      :aria-expanded="!isCollapsed"
      :aria-controls="navId"
      :aria-label="isCollapsed ? expandLabel : collapseLabel"
      @click="requestCollapsedChange(!isCollapsed)"
    >
      <span aria-hidden="true" class="cu-sidebar__toggle-icon" :data-direction="isCollapsed ? 'expand' : 'collapse'">
        <svg viewBox="0 0 24 24" class="cu-sidebar__toggle-svg">
          <path :d="isCollapsed ? 'M9 6l6 6-6 6' : 'M15 6l-6 6 6 6'" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        </svg>
      </span>
      <span class="cu-sidebar__label">{{ isCollapsed ? expandLabel : collapseLabel }}</span>
    </button>
  </aside>
</template>

<style src="./styles.css"></style>
