// packages/components-react/src/article-card/ArticleCard.tsx
import './styles.css'

export interface ArticleCardProps {
  title: string
  excerpt?: string
  author?: string
  date?: string
  coverSrc?: string
  coverAlt?: string
  href?: string
  readLabel?: string
  className?: string
}

export function ArticleCard({
  title,
  excerpt,
  author,
  date,
  coverSrc,
  coverAlt = '',
  href,
  readLabel = 'Read article',
  className,
}: ArticleCardProps) {
  const classes = ['cu-article-card', className].filter(Boolean).join(' ')
  return (
    <article className={classes} data-ai-role="article-card" data-ai-intent="group-content" data-ai-state="default">
      {coverSrc ? <img className="cu-article-card__cover" src={coverSrc} alt={coverAlt} loading="lazy" /> : null}
      <div className="cu-article-card__body">
        <h3 className="cu-article-card__title">{title}</h3>
        {excerpt ? <p className="cu-article-card__excerpt">{excerpt}</p> : null}
        <div className="cu-article-card__meta">
          {author ? <span className="cu-article-card__author">{author}</span> : null}
          {date ? <time className="cu-article-card__date">{date}</time> : null}
        </div>
        {href ? (
          <a className="cu-article-card__read" href={href} aria-label={`${readLabel}: ${title}`}>
            {readLabel}
          </a>
        ) : null}
      </div>
    </article>
  )
}

// packages/components-vue/src/article-card/ArticleCard.vue
<script lang="ts">
export interface ArticleCardProps {
  title: string
  excerpt?: string
  author?: string
  date?: string
  coverSrc?: string
  coverAlt?: string
  href?: string
  readLabel?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<ArticleCardProps>(), {
  coverAlt: '',
  readLabel: 'Read article'
})
const classes = computed(() => ["cu-article-card", props.class].filter(Boolean).join(' '))
</script>

<template>
  <article :class="classes" data-ai-role="article-card" data-ai-intent="group-content" data-ai-state="default">
    <img v-if="coverSrc" class="cu-article-card__cover" :src="coverSrc" :alt="coverAlt" loading="lazy" />
    <div class="cu-article-card__body">
      <h3 class="cu-article-card__title">{{ title }}</h3>
      <p v-if="excerpt" class="cu-article-card__excerpt">{{ excerpt }}</p>
      <div class="cu-article-card__meta">
        <span v-if="author" class="cu-article-card__author">{{ author }}</span>
        <time v-if="date" class="cu-article-card__date">{{ date }}</time>
      </div>
      <a v-if="href" class="cu-article-card__read" :href="href" :aria-label="readLabel + ': ' + title">{{ readLabel }}</a>
    </div>
  </article>
</template>

<style scoped src="./styles.css"></style>
