// chameleon-ui/packages/components-vue/src/menu/Menu.vue
<script lang="ts">
export interface MenuItem {
  label: string
  onClick: () => void
}

export interface MenuProps {
  triggerLabel: string
  items: MenuItem[]
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { PopoverPrimitive } from '@chameleon-ui/primitives-vue'

const props = defineProps<MenuProps>()
const classes = computed(() => ['cu-menu', props.class].filter(Boolean).join(' '))
</script>

<template>
  <PopoverPrimitive.Root>
    <PopoverPrimitive.Trigger class="cu-menu__trigger">{{ triggerLabel }}</PopoverPrimitive.Trigger>
    <PopoverPrimitive.Positioner>
      <PopoverPrimitive.Content :class="classes" data-ai-role="menu" data-ai-state="open" data-ai-intent="choose-action" role="menu">
        <ul class="cu-menu__list">
          <li v-for="(item, index) in items" :key="index" class="cu-menu__item">
            <button class="cu-menu__button" type="button" role="menuitem" @click="item.onClick">{{ item.label }}</button>
          </li>
        </ul>
      </PopoverPrimitive.Content>
    </PopoverPrimitive.Positioner>
  </PopoverPrimitive.Root>
</template>

<style scoped src="./styles.css"></style>

// packages/components/src/menu/Menu.tsx
import { PopoverPrimitive } from '@chameleon-ui/primitives'
import './styles.css'

export interface MenuItem {
  label: string
  onClick: () => void
}

export interface MenuProps {
  triggerLabel: string
  items: MenuItem[]
  className?: string
}

export function Menu({ triggerLabel, items, className }: MenuProps) {
  const classes = ['cu-menu', className].filter(Boolean).join(' ')
  return (
    <PopoverPrimitive.Root>
      <PopoverPrimitive.Trigger className="cu-menu__trigger">{triggerLabel}</PopoverPrimitive.Trigger>
      <PopoverPrimitive.Positioner>
        <PopoverPrimitive.Content className={classes} data-ai-role="menu" data-ai-state="open" data-ai-intent="choose-action" role="menu">
          <ul className="cu-menu__list">
            {items.map((item, index) => (
              <li className="cu-menu__item" key={index}>
                <button className="cu-menu__button" onClick={item.onClick} type="button" role="menuitem">
                  {item.label}
                </button>
              </li>
            ))}
          </ul>
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Positioner>
    </PopoverPrimitive.Root>
  )
}
