// chameleon-ui/packages/components-vue/src/label/Label.vue
<script lang="ts">
export interface LabelProps {
  htmlFor?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<LabelProps>()
const classes = computed(() => ["cu-label", props.class].filter(Boolean).join(' '))
</script>

<template>
  <label :class="classes" data-ai-role="label" data-ai-state="default" data-ai-intent="name-field" :for="htmlFor"><slot /></label>
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/label/Label.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface LabelProps {
  children: ReactNode
  htmlFor?: string
  className?: string
}

export function Label({ children, htmlFor, className }: LabelProps) {
  const classes = ['cu-label', className].filter(Boolean).join(' ')
  return <label className={classes} data-ai-role="label" data-ai-state="default" data-ai-intent="name-field" htmlFor={htmlFor}>{children}</label>
}
