// packages/components/src/image/Image.tsx
import { useState } from 'react'
import './styles.css'

export interface ImageProps {
  src: string
  alt: string
  caption?: string
  errorLabel?: string
  className?: string
}

export function Image({ src, alt, caption, errorLabel = 'Image failed to load', className }: ImageProps) {
  const [failed, setFailed] = useState(false)
  const classes = ['cu-image', className].filter(Boolean).join(' ')
  return (
    <figure className={classes} data-ai-role="image" data-ai-intent="signal-meaning" data-ai-state={failed ? 'error' : 'default'}>
      {failed ? (
        <div className="cu-image__fallback" role="img" aria-label={alt}>
          {errorLabel}
        </div>
      ) : (
        <img className="cu-image__img" src={src} alt={alt} loading="lazy" onError={() => setFailed(true)} />
      )}
      {caption ? <figcaption className="cu-image__caption">{caption}</figcaption> : null}
    </figure>
  )
}

// chameleon-ui/packages/components-vue/src/image/Image.vue
<script lang="ts">
export interface ImageProps {
  src: string
  alt: string
  caption?: string
  errorLabel?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'

const props = withDefaults(defineProps<ImageProps>(), {
  errorLabel: 'Image failed to load'
})
const failed = ref(false)
const classes = computed(() => ["cu-image", props.class].filter(Boolean).join(' '))
</script>

<template>
  <figure :class="classes" data-ai-role="image" data-ai-intent="signal-meaning" :data-ai-state="failed ? 'error' : 'default'">
    <div v-if="failed" class="cu-image__fallback" role="img" :aria-label="alt">{{ errorLabel }}</div>
    <img v-else class="cu-image__img" :src="src" :alt="alt" loading="lazy" @error="failed = true" />
    <figcaption v-if="caption" class="cu-image__caption">{{ caption }}</figcaption>
  </figure>
</template>

<style scoped src="./styles.css"></style>
