// chameleon-ui/packages/components-vue/src/number-input/NumberInput.vue
<script lang="ts">
export interface NumberInputProps {
  value: number
  label: string
  min?: number
  max?: number
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { FieldPrimitive } from '@chameleon-ui/primitives-vue'

const props = defineProps<NumberInputProps>()
const emit = defineEmits<{ change: [value: number] }>()
const classes = computed(() => ['cu-number-input', props.class].filter(Boolean).join(' '))

function onInput(event: Event) {
  emit('change', Number((event.currentTarget as HTMLInputElement).value))
}
</script>

<template>
  <FieldPrimitive.Root :class="classes" data-ai-role="number-input" data-ai-state="default" data-ai-intent="enter-quantity">
    <FieldPrimitive.Label class="cu-number-input__label">{{ label }}</FieldPrimitive.Label>
    <FieldPrimitive.Input
      class="cu-number-input__input"
      :max="max"
      :min="min"
      type="number"
      :model-value="String(value)"
      @input="onInput"
    />
  </FieldPrimitive.Root>
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/number-input/NumberInput.tsx
import { FieldPrimitive } from '@chameleon-ui/primitives'
import './styles.css'

export interface NumberInputProps {
  value: number
  onChange: (value: number) => void
  label: string
  min?: number
  max?: number
  className?: string
}

export function NumberInput({ value, onChange, label, min, max, className }: NumberInputProps) {
  const classes = ['cu-number-input', className].filter(Boolean).join(' ')
  return (
    <FieldPrimitive.Root className={classes} data-ai-role="number-input" data-ai-state="default" data-ai-intent="enter-quantity">
      <FieldPrimitive.Label className="cu-number-input__label">{label}</FieldPrimitive.Label>
      <FieldPrimitive.Input
        className="cu-number-input__input"
        max={max}
        min={min}
        onChange={(event) => onChange(Number(event.currentTarget.value))}
        type="number"
        value={value}
      />
    </FieldPrimitive.Root>
  )
}
