// packages/components-vue/src/hover-card/HoverCard.vue
<script lang="ts">
export interface HoverCardProps {
  class?: string
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { PopoverPrimitive } from '@chameleon-ui/primitives-vue'

const props = defineProps<HoverCardProps>()
const open = ref(false)
const classes = computed(() => ['cu-hover-card', props.class].filter(Boolean).join(' '))
</script>

<template>
  <PopoverPrimitive.Root :open="open" @open-change="(details: { open: boolean }) => (open = details.open)">
    <PopoverPrimitive.Trigger
      as-child
      class="cu-hover-card__trigger"
      @mouseenter="open = true"
      @mouseleave="open = false"
      @focus="open = true"
      @blur="open = false"
    >
      <slot name="trigger" />
    </PopoverPrimitive.Trigger>
    <PopoverPrimitive.Positioner>
      <PopoverPrimitive.Content
        :class="classes"
        data-ai-role="hover-card"
        data-ai-intent="preview-detail"
        :data-ai-state="open ? 'open' : 'closed'"
        @mouseenter="open = true"
        @mouseleave="open = false"
      >
        <slot />
      </PopoverPrimitive.Content>
    </PopoverPrimitive.Positioner>
  </PopoverPrimitive.Root>
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/hover-card/HoverCard.tsx
import { PopoverPrimitive } from '@chameleon-ui/primitives'
import { useState } from 'react'
import type { ReactNode } from 'react'
import './styles.css'

export interface HoverCardProps {
  trigger: ReactNode
  children: ReactNode
  className?: string
}

export function HoverCard({ trigger, children, className }: HoverCardProps) {
  const [open, setOpen] = useState(false)
  const classes = ['cu-hover-card', className].filter(Boolean).join(' ')

  return (
    <PopoverPrimitive.Root
      open={open}
      onOpenChange={(details) => setOpen(details.open)}
    >
      <PopoverPrimitive.Trigger
        asChild
        className="cu-hover-card__trigger"
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        onFocus={() => setOpen(true)}
        onBlur={() => setOpen(false)}
      >
        {trigger}
      </PopoverPrimitive.Trigger>
      <PopoverPrimitive.Positioner>
        <PopoverPrimitive.Content
          className={classes}
          data-ai-role="hover-card" data-ai-intent="preview-detail"
          data-ai-state={open ? 'open' : 'closed'}
          onMouseEnter={() => setOpen(true)}
          onMouseLeave={() => setOpen(false)}
        >
          {children}
        </PopoverPrimitive.Content>
      </PopoverPrimitive.Positioner>
    </PopoverPrimitive.Root>
  )
}
