// chameleon-ui/packages/components-vue/src/input/Input.vue
<script lang="ts">
export interface InputProps {
  label: string
  disabled?: boolean
  invalid?: boolean
  errorMessage?: string
  id?: string
  placeholder?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { InputPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<InputProps>(), {
  disabled: false,
  invalid: false,
  errorMessage: 'Please review this value.',
})

const model = defineModel<string>('modelValue', { default: '' })

const inputClasses = computed(() => ['cu-input', props.class].filter(Boolean).join(' '))
const dataAiState = computed(() =>
  props.invalid ? 'invalid' : props.disabled ? 'disabled' : 'default',
)

function updateValue(event: Event) {
  model.value = (event.target as HTMLInputElement).value
}
</script>

<template>
  <div class="cu-field" data-ai-role="input" :data-ai-state="dataAiState">
    <label :for="id" class="cu-field__label">{{ label }}</label>
    <InputPrimitive
      :id="id"
      :value="model"
      :class="inputClasses"
      :disabled="disabled"
      :aria-invalid="invalid || undefined"
      :placeholder="placeholder"
      @input="updateValue"
    />
    <span v-if="invalid" class="cu-field__error" aria-live="polite">{{ errorMessage }}</span>
  </div>
</template>

<style scoped src="./styles.css"></style>

// chameleon-ui/poc/base-ui/src/components/input/Input.tsx
import { Input as BaseInput } from '@base-ui/react/input'
import { useId } from 'react'
import type { ComponentPropsWithoutRef } from 'react'
import './styles.css'

export interface InputProps
  extends Omit<
    ComponentPropsWithoutRef<typeof BaseInput>,
    'className' | 'onChange' | 'onValueChange' | 'value'
  > {
  value: string
  onChange: (value: string) => void
  label: string
  invalid?: boolean
  errorMessage?: string
  className?: string
}

// @phase-1 migrate → packages/components/src/input/Input.tsx
export function Input({
  value,
  onChange,
  label,
  invalid = false,
  errorMessage = 'Please review this value.',
  className,
  id: providedId,
  disabled,
  ...props
}: InputProps) {
  const generatedId = useId()
  const id = providedId ?? generatedId
  const errorId = `${id}-error`
  const classes = ['cu-input', invalid && 'cu-input--invalid', className]
    .filter(Boolean)
    .join(' ')

  return (
    <div className="cu-field">
      <label className="cu-field__label" htmlFor={id}>
        {label}
      </label>
      <BaseInput
        {...props}
        id={id}
        value={value}
        disabled={disabled}
        aria-invalid={invalid || undefined}
        aria-describedby={invalid ? errorId : undefined}
        onValueChange={onChange}
        className={classes}
      />
      {invalid ? (
        <p className="cu-field__error" id={errorId}>
          {errorMessage}
        </p>
      ) : null}
    </div>
  )
}
