// packages/components-react/src/notification/Notification.tsx
import './styles.css'

export interface NotificationProps {
  title: string
  message: string
  variant?: 'info' | 'success' | 'warning' | 'error'
  onDismiss?: () => void
  dismissLabel?: string
  className?: string
}

export function Notification({
  title,
  message,
  variant = 'info',
  onDismiss,
  dismissLabel = 'Dismiss',
  className,
}: NotificationProps) {
  const classes = ['cu-notification', 'cu-notification--' + variant, className].filter(Boolean).join(' ')
  return (
    <div className={classes} role="status" data-ai-role="notification" data-ai-intent="notify-status" data-ai-state={variant}>
      <div className="cu-notification__body">
        <p className="cu-notification__title">{title}</p>
        <p className="cu-notification__message">{message}</p>
      </div>
      {onDismiss ? (
        <button type="button" className="cu-notification__dismiss" aria-label={dismissLabel} onClick={onDismiss}>
          ×
        </button>
      ) : null}
    </div>
  )
}

// chameleon-ui/packages/components-vue/src/notification/Notification.vue
<script lang="ts">
export interface NotificationProps {
  title: string
  message: string
  variant?: 'info' | 'success' | 'warning' | 'error'
  dismissLabel?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed, getCurrentInstance } from 'vue'

const props = withDefaults(defineProps<NotificationProps>(), {
  variant: 'info',
  dismissLabel: 'Dismiss'
})
const emit = defineEmits<{ dismiss: [] }>()
const instance = getCurrentInstance()
const hasDismiss = computed(() => typeof instance?.vnode.props?.onDismiss === 'function')
const classes = computed(() => ["cu-notification", 'cu-notification--' + props.variant, props.class].filter(Boolean).join(' '))
</script>

<template>
  <div :class="classes" role="status" data-ai-role="notification" data-ai-intent="notify-status" :data-ai-state="variant">
    <div class="cu-notification__body">
      <p class="cu-notification__title">{{ title }}</p>
      <p class="cu-notification__message">{{ message }}</p>
    </div>
    <button v-if="hasDismiss" type="button" class="cu-notification__dismiss" :aria-label="dismissLabel" @click="emit('dismiss')">×</button>
  </div>
</template>

<style scoped src="./styles.css"></style>
