// packages/components-react/src/app-shell/AppShell.tsx
import type { ReactNode } from 'react'
import './styles.css'

export type AppShellFooterPlacement = 'shell' | 'main' | 'auto'

export interface AppShellProps {
  header: ReactNode
  children: ReactNode
  /**
   * Three-end Navigation. One node; the named app-shell container moves it
   * from the block-end tab bar to the side column. Prefer this over composing
   * `sidebar` + `tabBar`.
   */
  navigation?: ReactNode
  /** Specialized side chrome that does not morph. Prefer `navigation`. */
  sidebar?: ReactNode
  /** Specialized compact chrome that does not morph. Prefer `navigation`. */
  tabBar?: ReactNode
  /**
   * Shell attribution (credits, legal). Prefer wrapping content in `Footer`.
   * Placement is controlled by `footerPlacement`.
   */
  footer?: ReactNode
  /**
   * Where footer lives relative to the main scrollport.
   * - `auto` (default): compact → end of main scroll; ≥48rem → shell-bottom chrome
   * - `shell`: always a dedicated grid row outside main scroll
   * - `main`: always flows at the end of main content
   */
  footerPlacement?: AppShellFooterPlacement
  sidebarLabel?: string
  /**
   * When false, chrome regions are plain divs (nested demos / embeds).
   * Default true — exposes one banner header + one main landmark.
   */
  landmarks?: boolean
  className?: string
}

export function AppShell({
  header,
  sidebar,
  children,
  navigation,
  tabBar,
  footer,
  footerPlacement = 'auto',
  sidebarLabel = 'Sidebar',
  landmarks = true,
  className,
}: AppShellProps) {
  const classes = ['cu-app-shell', className].filter(Boolean).join(' ')
  const HeaderTag = landmarks ? 'header' : 'div'
  const MainTag = landmarks ? 'main' : 'div'
  const FooterTag = landmarks ? 'footer' : 'div'
  const showFlow = Boolean(footer) && (footerPlacement === 'main' || footerPlacement === 'auto')
  const showChrome = Boolean(footer) && (footerPlacement === 'shell' || footerPlacement === 'auto')

  return (
    <div
      className={classes}
      data-cu-shell=""
      data-footer-placement={footer ? footerPlacement : undefined}
      data-ai-role="app-shell"
      data-ai-intent="layout-shell"
      data-ai-state="default"
    >
      <div className="cu-app-shell__frame">
        <HeaderTag className="cu-app-shell__header">{header}</HeaderTag>
        {navigation ? <div className="cu-app-shell__nav">{navigation}</div> : null}
        {sidebar ? (
          <aside aria-label={sidebarLabel} className="cu-app-shell__sidebar">
            {sidebar}
          </aside>
        ) : null}
        <MainTag className="cu-app-shell__main">
          {children}
          {showFlow ? (
            <div className="cu-app-shell__footer cu-app-shell__footer--flow" data-footer-host="main">
              {footer}
            </div>
          ) : null}
        </MainTag>
        {showChrome ? (
          <FooterTag className="cu-app-shell__footer cu-app-shell__footer--chrome" data-footer-host="shell">
            {footer}
          </FooterTag>
        ) : null}
        {tabBar ? <div className="cu-app-shell__tab-bar">{tabBar}</div> : null}
      </div>
    </div>
  )
}

// packages/components-vue/src/app-shell/AppShell.vue
<script lang="ts">
export type AppShellFooterPlacement = 'shell' | 'main' | 'auto'

export interface AppShellProps {
  sidebarLabel?: string
  /**
   * Where footer lives relative to the main scrollport.
   * - `auto` (default): compact → end of main scroll; ≥48rem → shell-bottom chrome
   * - `shell`: always a dedicated grid row outside main scroll
   * - `main`: always flows at the end of main content
   */
  footerPlacement?: AppShellFooterPlacement
  class?: string
}
</script>

<script setup lang="ts">
import { computed, useSlots } from 'vue'

const props = withDefaults(defineProps<AppShellProps>(), {
  sidebarLabel: 'Sidebar',
  footerPlacement: 'auto',
})

const slots = useSlots()
const classes = computed(() => ['cu-app-shell', props.class].filter(Boolean).join(' '))
const showFlow = computed(
  () => Boolean(slots.footer) && (props.footerPlacement === 'main' || props.footerPlacement === 'auto'),
)
const showChrome = computed(
  () => Boolean(slots.footer) && (props.footerPlacement === 'shell' || props.footerPlacement === 'auto'),
)
</script>

<template>
  <div
    :class="classes"
    data-cu-shell
    :data-footer-placement="slots.footer ? footerPlacement : undefined"
    data-ai-role="app-shell"
    data-ai-intent="layout-shell"
    data-ai-state="default"
  >
    <div class="cu-app-shell__frame">
      <header class="cu-app-shell__header">
        <slot name="header" />
      </header>
      <div v-if="slots.navigation" class="cu-app-shell__nav">
        <slot name="navigation" />
      </div>
      <aside v-if="slots.sidebar" :aria-label="sidebarLabel" class="cu-app-shell__sidebar">
        <slot name="sidebar" />
      </aside>
      <main class="cu-app-shell__main">
        <slot />
        <div
          v-if="showFlow"
          class="cu-app-shell__footer cu-app-shell__footer--flow"
          data-footer-host="main"
        >
          <slot name="footer" />
        </div>
      </main>
      <footer
        v-if="showChrome"
        class="cu-app-shell__footer cu-app-shell__footer--chrome"
        data-footer-host="shell"
      >
        <slot name="footer" />
      </footer>
      <div v-if="slots.tabBar" class="cu-app-shell__tab-bar">
        <slot name="tabBar" />
      </div>
    </div>
  </div>
</template>

<style src="./styles.css"></style>
