// chameleon-ui/packages/components-vue/src/link/Link.vue
<script lang="ts">
export interface LinkProps {
  href: string
  external?: boolean
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<LinkProps>(), {
  external: false
})
const classes = computed(() => ["cu-link", props.class].filter(Boolean).join(' '))
</script>

<template>
  <a
    :class="classes"
    data-ai-role="link"
    data-ai-state="default"
    data-ai-intent="navigate"
    :href="href"
    :rel="external ? 'noopener noreferrer' : undefined"
    :target="external ? '_blank' : undefined"
  ><slot /></a>
</template>

<style scoped src="./styles.css"></style>

// packages/components/src/link/Link.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface LinkProps {
  children: ReactNode
  href: string
  external?: boolean
  className?: string
}

export function Link({ children, href, external = false, className }: LinkProps) {
  const classes = ['cu-link', className].filter(Boolean).join(' ')
  return (
    <a
      className={classes}
      data-ai-role="link" data-ai-state="default" data-ai-intent="navigate"
      href={href}
      rel={external ? 'noopener noreferrer' : undefined}
      target={external ? '_blank' : undefined}
    >
      {children}
    </a>
  )
}
