// chameleon-ui/packages/components/src/tabs/Tabs.tsx
import { TabsPrimitive } from '@chameleon-ui/primitives'
import type { ReactNode } from 'react'
import './styles.css'

export interface TabItem {
  value: string
  label: string
  content: ReactNode
}

export interface TabsProps {
  items: TabItem[]
  defaultValue?: string
  value?: string
  onChange?: (value: string) => void
  className?: string
}

export function Tabs({ items, defaultValue, value, onChange, className }: TabsProps) {
  const classes = ['cu-tabs', className].filter(Boolean).join(' ')

  return (
    <TabsPrimitive.Root
      className={classes}
      data-ai-role="tabs"
      data-ai-intent="switch-view"
      data-ai-state={value ?? defaultValue ?? items[0]?.value ?? 'default'}
      defaultValue={defaultValue}
      value={value}
      lazyMount={false}
      unmountOnExit={false}
      onValueChange={(details) => onChange?.(details.value)}
    >
      <TabsPrimitive.List className="cu-tabs__list">
        {items.map((item) => (
          <TabsPrimitive.Trigger
            key={item.value}
            className="cu-tabs__trigger"
            value={item.value}
          >
            {item.label}
          </TabsPrimitive.Trigger>
        ))}
      </TabsPrimitive.List>
      {items.map((item) => (
        <TabsPrimitive.Content key={item.value} className="cu-tabs__content" value={item.value}>
          {item.content}
        </TabsPrimitive.Content>
      ))}
    </TabsPrimitive.Root>
  )
}

// packages/components-vue/src/tabs/Tabs.vue
<script lang="ts">
export interface TabItem {
  value: string
  label: string
  content: string
}

export interface TabsProps {
  items: TabItem[]
  defaultValue?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { TabsPrimitive } from '@chameleon-ui/primitives-vue'

const props = defineProps<TabsProps>()

const model = defineModel<string>('modelValue')

const classes = computed(() => ['cu-tabs', props.class].filter(Boolean).join(' '))
const dataAiState = computed(
  () => model.value ?? props.defaultValue ?? props.items[0]?.value ?? 'default',
)

function onValueChange(details: { value: string }) {
  model.value = details.value
}
</script>

<template>
  <TabsPrimitive.Root
    :class="classes"
    data-ai-role="tabs"
    data-ai-intent="switch-view"
    :data-ai-state="dataAiState"
    :default-value="defaultValue"
    :model-value="model"
    @value-change="onValueChange"
  >
    <TabsPrimitive.List class="cu-tabs__list">
      <TabsPrimitive.Trigger
        v-for="item in items"
        :key="item.value"
        class="cu-tabs__trigger"
        :value="item.value"
      >
        {{ item.label }}
      </TabsPrimitive.Trigger>
    </TabsPrimitive.List>
    <TabsPrimitive.Content
      v-for="item in items"
      :key="item.value"
      class="cu-tabs__content"
      :value="item.value"
    >
      {{ item.content }}
    </TabsPrimitive.Content>
  </TabsPrimitive.Root>
</template>

<style scoped src="./styles.css"></style>
