// chameleon-ui/packages/components-vue/src/accordion/Accordion.vue
<script lang="ts">
export interface AccordionItem {
  title: string
  content: string
}

export interface AccordionProps {
  items: AccordionItem[]
  multiple?: boolean
  class?: string
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'

const props = withDefaults(defineProps<AccordionProps>(), { multiple: false })
const openIndexes = ref<Set<number>>(new Set())
const classes = computed(() => ['cu-accordion', props.class].filter(Boolean).join(' '))

function isOpen(index: number) {
  return openIndexes.value.has(index)
}

function toggle(index: number) {
  const next = new Set(openIndexes.value)
  if (next.has(index)) next.delete(index)
  else {
    if (!props.multiple) next.clear()
    next.add(index)
  }
  openIndexes.value = next
}
</script>

<template>
  <div :class="classes" data-ai-role="accordion" data-ai-intent="expand-section" :data-ai-state="openIndexes.size > 0 ? 'open' : 'closed'">
    <div v-for="(item, index) in items" :key="index" class="cu-accordion__item">
      <button class="cu-accordion__trigger" type="button" :aria-expanded="isOpen(index)" @click="toggle(index)">{{ item.title }}</button>
      <div v-if="isOpen(index)" class="cu-accordion__content">{{ item.content }}</div>
    </div>
  </div>
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/accordion/Accordion.tsx
import { useState } from 'react'
import './styles.css'

export interface AccordionItem {
  title: string
  content: string
}

export interface AccordionProps {
  items: AccordionItem[]
  multiple?: boolean
  className?: string
}

export function Accordion({ items, multiple = false, className }: AccordionProps) {
  const [openIndexes, setOpenIndexes] = useState<Set<number>>(new Set())
  const classes = ['cu-accordion', className].filter(Boolean).join(' ')

  const toggle = (index: number) => {
    setOpenIndexes((prev) => {
      const next = new Set(prev)
      if (next.has(index)) {
        next.delete(index)
      } else {
        if (!multiple) next.clear()
        next.add(index)
      }
      return next
    })
  }

  return (
    <div className={classes} data-ai-role="accordion" data-ai-intent="expand-section" data-ai-state={openIndexes.size > 0 ? 'open' : 'closed'}>
      {items.map((item, index) => {
        const open = openIndexes.has(index)
        return (
          <div className="cu-accordion__item" key={index}>
            <button
              className="cu-accordion__trigger"
              onClick={() => toggle(index)}
              type="button"
              aria-expanded={open}
            >
              {item.title}
            </button>
            {open ? <div className="cu-accordion__content">{item.content}</div> : null}
          </div>
        )
      })}
    </div>
  )
}
