// chameleon-ui/packages/components/src/flow-node/FlowNode.tsx
import './styles.css'

export interface FlowNodeProps {
  id: string
  x: number
  y: number
  title: string
  status?: 'default' | 'active' | 'success' | 'failed'
  className?: string
}

export function FlowNode({ id, x, y, title, status = 'default', className }: FlowNodeProps) {
  const classes = ['cu-flow-node', 'cu-flow-node--' + status, className].filter(Boolean).join(' ')
  return (
    <div
      id={id}
      className={classes}
      data-ai-role="flow-node" data-ai-intent="group-content"
      data-ai-state={status}
      data-canvas-node
      style={{ transform: `translate(${x}px, ${y}px)` }}
    >
      <span className="cu-flow-node__port cu-flow-node__port--in" aria-hidden="true" />
      <span className="cu-flow-node__title">{title}</span>
      <span className="cu-flow-node__port cu-flow-node__port--out" aria-hidden="true" />
    </div>
  )
}

// chameleon-ui/packages/components-vue/src/flow-node/FlowNode.vue
<script lang="ts">
export interface FlowNodeProps {
  id: string
  x: number
  y: number
  title: string
  status?: 'default' | 'active' | 'success' | 'failed'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<FlowNodeProps>(), {
  status: 'default'
})
const classes = computed(() => ["cu-flow-node", 'cu-flow-node--' + props.status, props.class].filter(Boolean).join(' '))
const style = computed(() => ({ transform: `translate(${props.x}px, ${props.y}px)` }))
</script>

<template>
  <div :id="id" :class="classes" data-ai-role="flow-node" data-ai-intent="group-content" :data-ai-state="status" data-canvas-node :style="style">
    <span class="cu-flow-node__port cu-flow-node__port--in" aria-hidden="true" />
    <span class="cu-flow-node__title">{{ title }}</span>
    <span class="cu-flow-node__port cu-flow-node__port--out" aria-hidden="true" />
  </div>
</template>

<style scoped src="./styles.css"></style>
