// poc/base-ui/src/components/button/Button.tsx
import { Button as BaseButton } from '@base-ui/react/button'
import type { ComponentPropsWithoutRef } from 'react'
import './styles.css'

export type ButtonVariant = 'solid' | 'outline'
export type ButtonSize = 'sm' | 'md'

export interface ButtonProps
  extends Omit<ComponentPropsWithoutRef<typeof BaseButton>, 'className'> {
  variant?: ButtonVariant
  size?: ButtonSize
  className?: string
}

// @phase-1 migrate → packages/components/src/button/Button.tsx
export function Button({
  variant = 'solid',
  size = 'md',
  className,
  type = 'button',
  ...props
}: ButtonProps) {
  const classes = [
    'cu-button',
    `cu-button--${variant}`,
    `cu-button--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return <BaseButton {...props} type={type} className={classes} />
}

// chameleon-ui/packages/components-vue/src/button/Button.vue
<script lang="ts">
export interface ButtonProps {
  variant?: 'solid' | 'outline'
  size?: 'sm' | 'md'
  disabled?: boolean
  type?: 'button' | 'submit' | 'reset'
  intent?: 'submit' | 'confirm' | 'cancel'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { ButtonPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'solid',
  size: 'md',
  type: 'button',
})

const classes = computed(() =>
  ['cu-button', `cu-button--${props.variant}`, `cu-button--${props.size}`, props.class]
    .filter(Boolean)
    .join(' '),
)

const dataAiState = computed(() => (props.disabled ? 'disabled' : 'default'))
</script>

<template>
  <ButtonPrimitive
    :class="classes"
    :disabled="disabled"
    :type="type"
    data-ai-role="button"
    :data-ai-state="dataAiState"
    :data-ai-intent="intent"
    :data-variant="variant"
    :data-size="size"
  >
    <slot />
  </ButtonPrimitive>
</template>

<style scoped src="./styles.css"></style>
