// packages/components-react/src/input/Input.tsx
import { FieldPrimitive } from '@chameleon-ui/primitives'
import type { ComponentPropsWithoutRef } from 'react'
import './styles.css'

export interface InputProps
  extends Omit<ComponentPropsWithoutRef<'input'>, 'className' | 'onChange' | 'value'> {
  value: string
  onChange: (value: string) => void
  label: string
  disabled?: boolean
  invalid?: boolean
  errorMessage?: string
  className?: string
}

export function Input({
  value,
  onChange,
  label,
  disabled = false,
  invalid = false,
  errorMessage = 'Please review this value.',
  className,
  id,
  ...props
}: InputProps) {
  const classes = ['cu-input', className].filter(Boolean).join(' ')

  return (
    <FieldPrimitive.Root
      className="cu-field"
      data-ai-role="input" data-ai-intent="enter-text"
      data-ai-state={invalid ? 'invalid' : disabled ? 'disabled' : 'default'}
      disabled={disabled}
      id={id}
      invalid={invalid}
    >
      <FieldPrimitive.Label className="cu-field__label">{label}</FieldPrimitive.Label>
      <FieldPrimitive.Input
        {...props}
        className={classes}
        value={value}
        onChange={(event) => onChange(event.currentTarget.value)}
      />
      {invalid ? (
        <FieldPrimitive.ErrorText className="cu-field__error">{errorMessage}</FieldPrimitive.ErrorText>
      ) : null}
    </FieldPrimitive.Root>
  )
}

// packages/components-vue/src/input/Input.vue
<script lang="ts">
export interface InputProps {
  label: string
  disabled?: boolean
  invalid?: boolean
  errorMessage?: string
  id?: string
  placeholder?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { InputPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<InputProps>(), {
  disabled: false,
  invalid: false,
  errorMessage: 'Please review this value.',
})

const model = defineModel<string>('modelValue', { default: '' })

const inputClasses = computed(() => ['cu-input', props.class].filter(Boolean).join(' '))
const dataAiState = computed(() =>
  props.invalid ? 'invalid' : props.disabled ? 'disabled' : 'default',
)

function updateValue(event: Event) {
  model.value = (event.target as HTMLInputElement).value
}
</script>

<template>
  <div class="cu-field" data-ai-role="input" data-ai-intent="enter-text" :data-ai-state="dataAiState">
    <label :for="id" class="cu-field__label">{{ label }}</label>
    <InputPrimitive
      :id="id"
      :value="model"
      :class="inputClasses"
      :disabled="disabled"
      :aria-invalid="invalid || undefined"
      :placeholder="placeholder"
      @input="updateValue"
    />
    <span v-if="invalid" class="cu-field__error" aria-live="polite">{{ errorMessage }}</span>
  </div>
</template>

<style scoped src="./styles.css"></style>
