// chameleon-ui/packages/components-vue/src/separator/Separator.vue
<script lang="ts">
export interface SeparatorProps {
  orientation?: 'horizontal' | 'vertical'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<SeparatorProps>(), {
  orientation: 'horizontal'
})
const classes = computed(() => ["cu-separator", 'cu-separator--' + props.orientation, props.class].filter(Boolean).join(' '))
</script>

<template>
  <hr :class="classes" data-ai-role="separator" data-ai-intent="separate-items" :data-ai-state="orientation" :aria-orientation="orientation" />
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/separator/Separator.tsx
import './styles.css'

export interface SeparatorProps {
  orientation?: 'horizontal' | 'vertical'
  className?: string
}

export function Separator({ orientation = 'horizontal', className }: SeparatorProps) {
  const classes = ['cu-separator', 'cu-separator--' + orientation, className].filter(Boolean).join(' ')
  return <hr className={classes} data-ai-role="separator" data-ai-intent="separate-items" data-ai-state={orientation} aria-orientation={orientation} />
}
