// packages/components-react/src/pagination/Pagination.tsx
import './styles.css'

export interface PaginationProps {
  currentPage: number
  totalPages: number
  onChange: (page: number) => void
  className?: string
}

export function Pagination({ currentPage, totalPages, onChange, className }: PaginationProps) {
  const classes = ['cu-pagination', className].filter(Boolean).join(' ')
  const pages = Array.from({ length: totalPages }, (_, i) => i + 1)
  return (
    <nav aria-label="Pagination" className={classes} data-ai-role="pagination" data-ai-state="default" data-ai-intent="navigate-pages">
      <div className="cu-pagination__list">
        <button
          className="cu-pagination__button"
          disabled={currentPage <= 1}
          onClick={() => onChange(currentPage - 1)}
          type="button"
        >
          Previous
        </button>
        {pages.map((page) => (
          <button
            aria-current={page === currentPage ? 'page' : undefined}
            className={'cu-pagination__button' + (page === currentPage ? ' cu-pagination__button--current' : '')}
            key={page}
            onClick={() => onChange(page)}
            type="button"
          >
            {page}
          </button>
        ))}
        <button
          className="cu-pagination__button"
          disabled={currentPage >= totalPages}
          onClick={() => onChange(currentPage + 1)}
          type="button"
        >
          Next
        </button>
      </div>
    </nav>
  )
}

// chameleon-ui/packages/components-vue/src/pagination/Pagination.vue
<script lang="ts">
export interface PaginationProps {
  currentPage: number
  totalPages: number
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<PaginationProps>()
const emit = defineEmits<{ change: [page: number] }>()
const classes = computed(() => ['cu-pagination', props.class].filter(Boolean).join(' '))
const pages = computed(() => Array.from({ length: props.totalPages }, (_, i) => i + 1))
</script>

<template>
  <nav aria-label="Pagination" :class="classes" data-ai-role="pagination" data-ai-state="default" data-ai-intent="navigate-pages">
    <div class="cu-pagination__list">
      <button class="cu-pagination__button" type="button" :disabled="currentPage <= 1" @click="emit('change', currentPage - 1)">Previous</button>
      <button
        v-for="page in pages"
        :key="page"
        :aria-current="page === currentPage ? 'page' : undefined"
        :class="'cu-pagination__button' + (page === currentPage ? ' cu-pagination__button--current' : '')"
        type="button"
        @click="emit('change', page)"
      >{{ page }}</button>
      <button class="cu-pagination__button" type="button" :disabled="currentPage >= totalPages" @click="emit('change', currentPage + 1)">Next</button>
    </div>
  </nav>
</template>

<style scoped src="./styles.css"></style>
