// packages/components-react/src/gauge/Gauge.tsx
import './styles.css'

export interface GaugeProps {
  value: number
  max?: number
  label: string
  valueLabel?: string
  className?: string
}

const RADIUS = 70
const CENTER = 80

export function Gauge({ value, max = 100, label, valueLabel, className }: GaugeProps) {
  const classes = ['cu-gauge', className].filter(Boolean).join(' ')
  const clamped = Math.min(max, Math.max(0, value))
  const percent = max > 0 ? (clamped / max) * 100 : 0
  const startX = CENTER - RADIUS
  const endX = CENTER + RADIUS

  return (
    <div className={classes} data-ai-role="gauge" data-ai-intent="visualize-data" data-ai-state="default">
      <svg
        className="cu-gauge__svg"
        viewBox={`0 0 ${CENTER * 2} ${CENTER + 12}`}
        role="meter"
        aria-label={label}
        aria-valuemin={0}
        aria-valuemax={max}
        aria-valuenow={clamped}
      >
        <path
          className="cu-gauge__track"
          d={`M ${startX} ${CENTER} A ${RADIUS} ${RADIUS} 0 0 1 ${endX} ${CENTER}`}
          pathLength={100}
        />
        <path
          className="cu-gauge__fill"
          d={`M ${startX} ${CENTER} A ${RADIUS} ${RADIUS} 0 0 1 ${endX} ${CENTER}`}
          pathLength={100}
          strokeDasharray={`${percent} 100`}
        />
        <text className="cu-gauge__value" x={CENTER} y={CENTER - 8} textAnchor="middle">
          {valueLabel ?? String(clamped)}
        </text>
      </svg>
    </div>
  )
}

// packages/components-vue/src/gauge/Gauge.vue
<script lang="ts">
export interface GaugeProps {
  value: number
  max?: number
  label: string
  valueLabel?: string
  class?: string
}

const RADIUS = 70
const CENTER = 80
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<GaugeProps>(), { max: 100 })
const classes = computed(() => ['cu-gauge', props.class].filter(Boolean).join(' '))
const clamped = computed(() => Math.min(props.max, Math.max(0, props.value)))
const percent = computed(() => (props.max > 0 ? (clamped.value / props.max) * 100 : 0))
const startX = CENTER - RADIUS
const endX = CENTER + RADIUS
const arc = `M ${startX} ${CENTER} A ${RADIUS} ${RADIUS} 0 0 1 ${endX} ${CENTER}`
</script>

<template>
  <div :class="classes" data-ai-role="gauge" data-ai-intent="visualize-data" data-ai-state="default">
    <svg class="cu-gauge__svg" :viewBox="'0 0 ' + CENTER * 2 + ' ' + (CENTER + 12)" role="meter" :aria-label="label" :aria-valuemin="0" :aria-valuemax="max" :aria-valuenow="clamped">
      <path class="cu-gauge__track" :d="arc" :pathLength="100" />
      <path class="cu-gauge__fill" :d="arc" :pathLength="100" :stroke-dasharray="percent + ' 100'" />
      <text class="cu-gauge__value" :x="CENTER" :y="CENTER - 8" text-anchor="middle">{{ valueLabel ?? String(clamped) }}</text>
    </svg>
  </div>
</template>

<style scoped src="./styles.css"></style>
