// chameleon-ui/packages/components-vue/src/description-list/DescriptionList.vue
<script lang="ts">
export interface DescriptionListItem {
  term: string
  description: string
}

export interface DescriptionListProps {
  items: DescriptionListItem[]
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<DescriptionListProps>()
const classes = computed(() => ["cu-description-list", props.class].filter(Boolean).join(' '))
</script>

<template>
  <dl :class="classes" data-ai-role="description-list" data-ai-state="default" data-ai-intent="inspect-details">
    <div v-for="(item, index) in items" :key="index" class="cu-description-list__group">
      <dt class="cu-description-list__term">{{ item.term }}</dt>
      <dd class="cu-description-list__detail">{{ item.description }}</dd>
    </div>
  </dl>
</template>

<style scoped src="./styles.css"></style>

// packages/components/src/description-list/DescriptionList.tsx
import './styles.css'

export interface DescriptionListItem {
  term: string
  description: string
}

export interface DescriptionListProps {
  items: DescriptionListItem[]
  className?: string
}

export function DescriptionList({ items, className }: DescriptionListProps) {
  const classes = ['cu-description-list', className].filter(Boolean).join(' ')
  return (
    <dl className={classes} data-ai-role="description-list" data-ai-state="default" data-ai-intent="inspect-details">
      {items.map((item, index) => (
        <div className="cu-description-list__group" key={index}>
          <dt className="cu-description-list__term">{item.term}</dt>
          <dd className="cu-description-list__detail">{item.description}</dd>
        </div>
      ))}
    </dl>
  )
}
