// chameleon-ui/packages/components/src/divider/Divider.tsx
import './styles.css'

export interface DividerProps {
  className?: string
}

export function Divider({ className }: DividerProps) {
  const classes = ['cu-divider', className].filter(Boolean).join(' ')
  return <hr className={classes} data-ai-role="divider" data-ai-state="default" data-ai-intent="separate-sections" />
}

// packages/components-vue/src/divider/Divider.vue
<script lang="ts">
export interface DividerProps {
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<DividerProps>()
const classes = computed(() => ["cu-divider", props.class].filter(Boolean).join(' '))
</script>

<template>
  <hr :class="classes" data-ai-role="divider" data-ai-state="default" data-ai-intent="separate-sections" />
</template>

<style scoped src="./styles.css"></style>
