// packages/components-react/src/masonry/Masonry.tsx
import type { ReactNode } from 'react'
import './styles.css'

export type MasonryGap = 'sm' | 'md' | 'lg'

export interface MasonryProps {
  children: ReactNode
  columns?: 2 | 3 | 4
  gap?: MasonryGap
  className?: string
}

export function Masonry({ children, columns = 3, gap = 'md', className }: MasonryProps) {
  const classes = [
    'cu-masonry',
    'cu-masonry--columns-' + columns,
    'cu-masonry--gap-' + gap,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div
      className={classes}
      data-ai-role="masonry"
      data-ai-intent="layout-columns"
      data-ai-state="default"
      data-columns={columns}
    >
      <div className="cu-masonry__track">{children}</div>
    </div>
  )
}

// chameleon-ui/packages/components-vue/src/masonry/Masonry.vue
<script lang="ts">
export type MasonryGap = 'sm' | 'md' | 'lg'

export interface MasonryProps {
  columns?: 2 | 3 | 4
  gap?: MasonryGap
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<MasonryProps>(), {
  columns: 3,
  gap: 'md'
})
const classes = computed(() =>
  ['cu-masonry', 'cu-masonry--columns-' + props.columns, 'cu-masonry--gap-' + props.gap, props.class].filter(Boolean).join(' '),
)
</script>

<template>
  <div :class="classes" data-ai-role="masonry" data-ai-intent="layout-columns" data-ai-state="default" :data-columns="columns">
    <div class="cu-masonry__track"><slot /></div>
  </div>
</template>

<style scoped src="./styles.css"></style>
