// packages/components/src/date-picker/DatePicker.tsx
import { useId, useRef, useState } from 'react'
import './styles.css'

export interface DatePickerProps {
  value: string
  onChange: (isoDate: string) => void
  label: string
  locale?: string
  previousMonthLabel?: string
  nextMonthLabel?: string
  className?: string
}

const DAY_MS = 86_400_000
/** 2023-01-01 was a Sunday; anchor for Intl-derived weekday names. */
const SUNDAY = Date.UTC(2023, 0, 1)

function parseISODate(value: string | undefined): { year: number; month: number } {
  const parts = value?.split('-').map(Number) ?? []
  const now = new Date()
  return {
    year: parts[0] || now.getUTCFullYear(),
    month: parts[1] ? parts[1] - 1 : now.getUTCMonth(),
  }
}

function toISODate(year: number, month: number, day: number): string {
  return `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
}

function daysInMonth(year: number, month: number): number {
  return new Date(Date.UTC(year, month + 1, 0)).getUTCDate()
}

/** Locale first day of week normalized to 0 (Sunday) … 6 (Saturday). */
function firstDayOfWeek(locale: string): number {
  try {
    const info = (new Intl.Locale(locale) as { weekInfo?: { firstDay?: number } }).weekInfo
    return (info?.firstDay ?? 7) % 7
  } catch {
    return 0
  }
}

function weekdayNames(locale: string, firstDay: number): string[] {
  const format = new Intl.DateTimeFormat(locale, { weekday: 'short', timeZone: 'UTC' })
  return Array.from({ length: 7 }, (_, index) => format.format(new Date(SUNDAY + ((firstDay + index) % 7) * DAY_MS)))
}

export function DatePicker({
  value,
  onChange,
  label,
  locale = 'en',
  previousMonthLabel = 'Previous month',
  nextMonthLabel = 'Next month',
  className,
}: DatePickerProps) {
  const [open, setOpen] = useState(false)
  const [view, setView] = useState(() => parseISODate(value))
  const inputRef = useRef<HTMLInputElement>(null)
  const inputId = useId()
  const classes = ['cu-date-picker', className].filter(Boolean).join(' ')

  const dateFormat = new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeZone: 'UTC' })
  const monthFormat = new Intl.DateTimeFormat(locale, { month: 'long', year: 'numeric', timeZone: 'UTC' })
  const dayFormat = new Intl.NumberFormat(locale)
  const parsed = value ? new Date(`${value}T00:00:00Z`) : null
  const display = parsed && !Number.isNaN(parsed.getTime()) ? dateFormat.format(parsed) : ''
  const headline = monthFormat.format(new Date(Date.UTC(view.year, view.month, 1)))
  const firstDay = firstDayOfWeek(locale)
  const weekdays = weekdayNames(locale, firstDay)
  const leadingBlanks = (new Date(Date.UTC(view.year, view.month, 1)).getUTCDay() - firstDay + 7) % 7
  const dayCount = daysInMonth(view.year, view.month)
  const cells: (number | null)[] = [
    ...Array.from({ length: leadingBlanks }, () => null),
    ...Array.from({ length: dayCount }, (_, index) => index + 1),
  ]
  const weeks: (number | null)[][] = []
  for (let index = 0; index < cells.length; index += 7) {
    weeks.push(cells.slice(index, index + 7))
  }

  const close = () => {
    setOpen(false)
    inputRef.current?.focus()
  }

  const move = (delta: number) => {
    setView((current) => {
      const next = new Date(Date.UTC(current.year, current.month + delta, 1))
      return { year: next.getUTCFullYear(), month: next.getUTCMonth() }
    })
  }

  const pick = (day: number) => {
    onChange(toISODate(view.year, view.month, day))
    close()
  }

  return (
    <div className={classes} data-ai-role="date-picker" data-ai-intent="pick-datetime" data-ai-state={open ? 'open' : 'closed'}>
      <label className="cu-date-picker__label" htmlFor={inputId}>
        {label}
      </label>
      <div className="cu-date-picker__field">
        <input
          ref={inputRef}
          id={inputId}
          className="cu-date-picker__input"
          type="text"
          readOnly
          value={display}
          aria-expanded={open}
          aria-haspopup="dialog"
          onClick={() => {
            setView(parseISODate(value))
            setOpen(true)
          }}
          onKeyDown={(event) => {
            if (event.key === 'Escape') close()
            if (event.key === 'Enter' || event.key === ' ') {
              event.preventDefault()
              setView(parseISODate(value))
              setOpen(true)
            }
          }}
        />
        <button
          type="button"
          className="cu-date-picker__toggle"
          aria-label={label}
          onClick={() => {
            setView(parseISODate(value))
            setOpen((current) => !current)
          }}
        >
          <span aria-hidden="true">▾</span>
        </button>
      </div>
      {open ? (
        <div
          className="cu-date-picker__popover"
          role="dialog"
          aria-label={headline}
          onKeyDown={(event) => {
            if (event.key === 'Escape') close()
          }}
        >
          <div className="cu-date-picker__header">
            <button type="button" className="cu-date-picker__nav" aria-label={previousMonthLabel} onClick={() => move(-1)}>
              <span aria-hidden="true">‹</span>
            </button>
            <span className="cu-date-picker__headline">{headline}</span>
            <button type="button" className="cu-date-picker__nav" aria-label={nextMonthLabel} onClick={() => move(1)}>
              <span aria-hidden="true">›</span>
            </button>
          </div>
          <div className="cu-date-picker__grid" role="grid" aria-label={headline}>
            <div className="cu-date-picker__weekdays" role="row">
              {weekdays.map((weekday, index) => (
                <span key={weekday + index} className="cu-date-picker__weekday" role="columnheader">
                  {weekday}
                </span>
              ))}
            </div>
            {weeks.map((week, weekIndex) => (
              <div key={weekIndex} className="cu-date-picker__week" role="row">
                {week.map((day, dayIndex) =>
                  day === null ? (
                    <span
                      key={`blank-${weekIndex}-${dayIndex}`}
                      className="cu-date-picker__blank"
                      role="gridcell"
                      aria-hidden="true"
                    />
                  ) : (
                    <span key={day} className="cu-date-picker__cell" role="gridcell">
                      <button
                        type="button"
                        className="cu-date-picker__day"
                        aria-selected={value === toISODate(view.year, view.month, day)}
                        onClick={() => pick(day)}
                      >
                        {dayFormat.format(day)}
                      </button>
                    </span>
                  ),
                )}
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  )
}

// packages/components-vue/src/date-picker/DatePicker.vue
<script lang="ts">
export interface DatePickerProps {
  value: string
  label: string
  locale?: string
  previousMonthLabel?: string
  nextMonthLabel?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed, ref, useId } from 'vue'
import { buildWeeks, firstDayOfWeek, parseISODate, toISODate, weekdayNames } from '../calendar/calendar-math.js'

const props = withDefaults(defineProps<DatePickerProps>(), {
  locale: 'en',
  previousMonthLabel: 'Previous month',
  nextMonthLabel: 'Next month',
})
const emit = defineEmits<{ change: [isoDate: string] }>()
const open = ref(false)
const view = ref(parseISODate(props.value))
const inputRef = ref<HTMLInputElement | null>(null)
const inputId = useId()
const classes = computed(() => ['cu-date-picker', props.class].filter(Boolean).join(' '))
const dateFormat = computed(() => new Intl.DateTimeFormat(props.locale, { dateStyle: 'medium', timeZone: 'UTC' }))
const monthFormat = computed(
  () => new Intl.DateTimeFormat(props.locale, { month: 'long', year: 'numeric', timeZone: 'UTC' }),
)
const dayFormat = computed(() => new Intl.NumberFormat(props.locale))
const display = computed(() => {
  const parsed = props.value ? new Date(`${props.value}T00:00:00Z`) : null
  return parsed && !Number.isNaN(parsed.getTime()) ? dateFormat.value.format(parsed) : ''
})
const headline = computed(() => monthFormat.value.format(new Date(Date.UTC(view.value.year, view.value.month, 1))))
const firstDay = computed(() => firstDayOfWeek(props.locale))
const weekdays = computed(() => weekdayNames(props.locale, firstDay.value))
const weeks = computed(() => buildWeeks(view.value.year, view.value.month, firstDay.value))

function close() {
  open.value = false
  inputRef.value?.focus()
}

function openPicker() {
  view.value = parseISODate(props.value)
  open.value = true
}

function move(delta: number) {
  const next = new Date(Date.UTC(view.value.year, view.value.month + delta, 1))
  view.value = { year: next.getUTCFullYear(), month: next.getUTCMonth() }
}

function pick(day: number) {
  emit('change', toISODate(view.value.year, view.value.month, day))
  close()
}

function onFieldKey(event: KeyboardEvent) {
  if (event.key === 'Escape') close()
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    openPicker()
  }
}
</script>

<template>
  <div :class="classes" data-ai-role="date-picker" data-ai-intent="pick-datetime" :data-ai-state="open ? 'open' : 'closed'">
    <label class="cu-date-picker__label" :for="inputId">{{ label }}</label>
    <div class="cu-date-picker__field">
      <input
        :id="inputId"
        ref="inputRef"
        class="cu-date-picker__input"
        type="text"
        readonly
        :value="display"
        :aria-expanded="open"
        aria-haspopup="dialog"
        @click="openPicker"
        @keydown="onFieldKey"
      />
      <button type="button" class="cu-date-picker__toggle" :aria-label="label" @click="open ? close() : openPicker()">
        <span aria-hidden="true">▾</span>
      </button>
    </div>
    <div v-if="open" class="cu-date-picker__popover" role="dialog" :aria-label="headline" @keydown.escape="close">
      <div class="cu-date-picker__header">
        <button type="button" class="cu-date-picker__nav" :aria-label="previousMonthLabel" @click="move(-1)">
          <span aria-hidden="true">‹</span>
        </button>
        <span class="cu-date-picker__headline">{{ headline }}</span>
        <button type="button" class="cu-date-picker__nav" :aria-label="nextMonthLabel" @click="move(1)">
          <span aria-hidden="true">›</span>
        </button>
      </div>
      <div class="cu-date-picker__grid" role="grid" :aria-label="headline">
        <div class="cu-date-picker__weekdays" role="row">
          <span v-for="(weekday, index) in weekdays" :key="weekday + index" class="cu-date-picker__weekday" role="columnheader">
            {{ weekday }}
          </span>
        </div>
        <div v-for="(week, weekIndex) in weeks" :key="weekIndex" class="cu-date-picker__week" role="row">
          <template v-for="(day, dayIndex) in week" :key="day ?? 'blank-' + weekIndex + '-' + dayIndex">
            <span v-if="day === null" class="cu-date-picker__blank" role="gridcell" aria-hidden="true" />
            <span v-else class="cu-date-picker__cell" role="gridcell">
              <button
                type="button"
                class="cu-date-picker__day"
                :aria-selected="value === toISODate(view.year, view.month, day)"
                @click="pick(day)"
              >
                {{ dayFormat.format(day) }}
              </button>
            </span>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped src="./styles.css"></style>
