// packages/components/src/collapse/Collapse.tsx
import { useState } from 'react'
import type { ReactNode } from 'react'
import './styles.css'

export interface CollapseProps {
  title: string
  children: ReactNode
  defaultOpen?: boolean
  className?: string
}

export function Collapse({ title, children, defaultOpen = false, className }: CollapseProps) {
  const [open, setOpen] = useState(defaultOpen)
  const classes = ['cu-collapse', className].filter(Boolean).join(' ')
  return (
    <div className={classes} data-ai-role="collapse" data-ai-intent="toggle-visibility" data-ai-state={open ? 'open' : 'closed'}>
      <button className="cu-collapse__trigger" onClick={() => setOpen(!open)} type="button" aria-expanded={open}>
        {title}
      </button>
      {open ? <div className="cu-collapse__content">{children}</div> : null}
    </div>
  )
}

// packages/components-vue/src/collapse/Collapse.vue
<script lang="ts">
export interface CollapseProps {
  title: string
  defaultOpen?: boolean
  class?: string
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'

const props = withDefaults(defineProps<CollapseProps>(), {
  defaultOpen: false
})
const open = ref(props.defaultOpen)
const classes = computed(() => ["cu-collapse", props.class].filter(Boolean).join(' '))
</script>

<template>
  <div :class="classes" data-ai-role="collapse" data-ai-intent="toggle-visibility" :data-ai-state="open ? 'open' : 'closed'">
    <button class="cu-collapse__trigger" type="button" :aria-expanded="open" @click="open = !open">{{ title }}</button>
    <div v-if="open" class="cu-collapse__content"><slot /></div>
  </div>
</template>

<style scoped src="./styles.css"></style>
