// chameleon-ui/packages/components-vue/src/grid/Grid.vue
<script lang="ts">
export interface GridProps {
  columns?: number
  gap?: 'none' | 'sm' | 'md' | 'lg'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<GridProps>(), {
  columns: 1,
  gap: 'md',
})

const classes = computed(() =>
  ['cu-grid', `cu-grid--gap-${props.gap}`, props.class].filter(Boolean).join(' '),
)

const gridStyle = computed(() => ({
  gridTemplateColumns: `repeat(${props.columns}, minmax(0, 1fr))`,
}))
</script>

<template>
  <div
    :class="classes"
    data-ai-role="grid"
    data-ai-state="default"
    data-ai-intent="layout-columns"
    :style="gridStyle"
  >
    <slot />
  </div>
</template>

<style scoped src="./styles.css"></style>

// packages/components-react/src/grid/Grid.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface GridProps {
  children: ReactNode
  columns?: number
  gap?: 'none' | 'sm' | 'md' | 'lg'
  className?: string
}

export function Grid({ children, columns = 1, gap = 'md', className }: GridProps) {
  const classes = ['cu-grid', 'cu-grid--gap-' + gap, className].filter(Boolean).join(' ')
  return (
    <div
      className={classes}
      data-ai-role="grid" data-ai-state="default" data-ai-intent="layout-columns"
      style={{ gridTemplateColumns: 'repeat(' + columns + ', minmax(0, 1fr))' }}
    >
      {children}
    </div>
  )
}
