// chameleon-ui/packages/components-vue/src/button/Button.vue
<script lang="ts">
export interface ButtonProps {
  variant?: 'solid' | 'outline'
  size?: 'sm' | 'md'
  disabled?: boolean
  type?: 'button' | 'submit' | 'reset'
  intent?: 'submit' | 'confirm' | 'cancel'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { ButtonPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'solid',
  size: 'md',
  type: 'button',
})

const classes = computed(() =>
  ['cu-button', `cu-button--${props.variant}`, `cu-button--${props.size}`, props.class]
    .filter(Boolean)
    .join(' '),
)

const dataAiState = computed(() => (props.disabled ? 'disabled' : 'default'))
</script>

<template>
  <ButtonPrimitive
    :class="classes"
    :disabled="disabled"
    :type="type"
    data-ai-role="button"
    :data-ai-state="dataAiState"
    :data-ai-intent="intent"
    :data-variant="variant"
    :data-size="size"
  >
    <slot />
  </ButtonPrimitive>
</template>

<style scoped src="./styles.css"></style>

// packages/components/src/button/Button.tsx
import { ButtonPrimitive } from '@chameleon-ui/primitives'
import type { ButtonPrimitiveProps } from '@chameleon-ui/primitives'
import './styles.css'

export interface ButtonProps extends Omit<ButtonPrimitiveProps, 'className'> {
  variant?: 'solid' | 'outline'
  size?: 'sm' | 'md'
  className?: string
}

export function Button({
  variant = 'solid',
  size = 'md',
  className,
  type = 'button',
  disabled,
  ...props
}: ButtonProps) {
  const classes = ['cu-button', `cu-button--${variant}`, `cu-button--${size}`, className]
    .filter(Boolean)
    .join(' ')

  return (
    <ButtonPrimitive
      className={classes}
      data-ai-role="button" data-ai-intent="submit"
      data-ai-state={disabled ? 'disabled' : 'default'}
      data-size={size}
      data-variant={variant}
      disabled={disabled}
      type={type}
      {...props}
    />
  )
}
