// packages/components-vue/src/button/Button.vue
<script lang="ts">
export type ButtonVariant = 'solid' | 'outline' | 'ghost'
export type ButtonSize = 'sm' | 'md'
export type ButtonTone = 'brand' | 'danger'

export interface ButtonProps {
  variant?: ButtonVariant
  size?: ButtonSize
  tone?: ButtonTone
  disabled?: boolean
  loading?: boolean
  type?: 'button' | 'submit' | 'reset'
  intent?: 'submit' | 'confirm' | 'cancel'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { ButtonPrimitive } from '@chameleon-ui/primitives-vue'

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'solid',
  size: 'md',
  tone: 'brand',
  type: 'button',
  loading: false,
  intent: 'submit',
})

const classes = computed(() =>
  [
    'cu-button',
    `cu-button--${props.variant}`,
    `cu-button--${props.size}`,
    `cu-button--tone-${props.tone}`,
    props.loading ? 'cu-button--loading' : '',
    props.class,
  ]
    .filter(Boolean)
    .join(' '),
)

const dataAiState = computed(() => {
  if (props.loading) return 'loading'
  if (props.disabled) return 'disabled'
  return 'default'
})

const isDisabled = computed(() => Boolean(props.disabled || props.loading))
</script>

<template>
  <ButtonPrimitive
    :class="classes"
    :disabled="isDisabled"
    :type="type"
    :aria-busy="loading || undefined"
    data-ai-role="button"
    :data-ai-state="dataAiState"
    :data-ai-intent="intent"
    :data-variant="variant"
    :data-size="size"
    :data-tone="tone"
  >
    <span v-if="loading" aria-hidden="true" class="cu-button__spinner" />
    <span v-else-if="$slots.icon" aria-hidden="true" class="cu-button__icon">
      <slot name="icon" />
    </span>
    <slot />
  </ButtonPrimitive>
</template>

<style scoped src="./styles.css"></style>

// packages/components/src/button/Button.tsx
import { ButtonPrimitive } from '@chameleon-ui/primitives'
import type { ButtonPrimitiveProps } from '@chameleon-ui/primitives'
import type { ReactNode } from 'react'
import './styles.css'

export type ButtonVariant = 'solid' | 'outline' | 'ghost'
export type ButtonSize = 'sm' | 'md'
export type ButtonTone = 'brand' | 'danger'

export interface ButtonProps extends Omit<ButtonPrimitiveProps, 'className'> {
  variant?: ButtonVariant
  size?: ButtonSize
  /** Semantic color. Does not change the button role. */
  tone?: ButtonTone
  /** Shows a spinner, sets aria-busy, and blocks activation. */
  loading?: boolean
  /** Leading visual. Provide a visible text child or aria-label. */
  icon?: ReactNode
  className?: string
}

function aiState(disabled?: boolean, loading?: boolean): 'loading' | 'disabled' | 'default' {
  if (loading) return 'loading'
  if (disabled) return 'disabled'
  return 'default'
}

export function Button({
  variant = 'solid',
  size = 'md',
  tone = 'brand',
  loading = false,
  icon,
  className,
  type = 'button',
  disabled,
  children,
  ...props
}: ButtonProps) {
  const isDisabled = Boolean(disabled || loading)
  const classes = [
    'cu-button',
    `cu-button--${variant}`,
    `cu-button--${size}`,
    `cu-button--tone-${tone}`,
    loading ? 'cu-button--loading' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <ButtonPrimitive
      className={classes}
      data-ai-role="button"
      data-ai-intent="submit"
      data-ai-state={aiState(disabled, loading)}
      data-size={size}
      data-variant={variant}
      data-tone={tone}
      disabled={isDisabled}
      aria-busy={loading || undefined}
      type={type}
      {...props}
    >
      {loading ? <span aria-hidden="true" className="cu-button__spinner" /> : null}
      {!loading && icon ? (
        <span aria-hidden="true" className="cu-button__icon">
          {icon}
        </span>
      ) : null}
      {children}
    </ButtonPrimitive>
  )
}
