// templates/external-vite-react/src/App.tsx
import { useState } from 'react'
import {
  AppShell,
  Button,
  Card,
  Navigation,
  NavigationBar,
  Stack,
  ToastProvider,
  useTabStacks,
  useToast,
} from '@chameleon-ui/react'

const tabs = [
  { value: 'home', title: 'Home' },
  { value: 'inbox', title: 'Inbox' },
]

export function App() {
  return (
    <ToastProvider>
      <Shell />
    </ToastProvider>
  )
}

function Shell() {
  const stacks = useTabStacks(tabs)
  const screen = stacks.current.id === 'detail' ? <Detail /> : stacks.tab === 'inbox' ? <Inbox /> : <Home onOpen={() => stacks.push({ id: 'detail', title: 'Detail' })} />

  return (
    <AppShell
      header={
        <NavigationBar
          backLabel={stacks.previous?.title}
          onBack={stacks.canPop ? stacks.pop : undefined}
          title={stacks.current.title}
        />
      }
      navigation={
        <Navigation
          activeValue={stacks.tab}
          items={tabs.map((item) => ({ value: item.value, label: item.title }))}
          label="Main"
          onSelect={stacks.selectTab}
        />
      }
    >
      {screen}
    </AppShell>
  )
}

function Home({ onOpen }: { onOpen: () => void }) {
  const toast = useToast()
  const [saving, setSaving] = useState(false)

  return (
    <Card>
      <Stack gap="2">
      <p>Official external Vite template. Do not compose Sidebar + TabBar.</p>
      <Button
        loading={saving}
        onClick={() => {
          setSaving(true)
          window.setTimeout(() => {
            setSaving(false)
            toast.push({
              title: 'Saved',
              description: 'Queued toast from ToastProvider.',
              status: 'success',
            })
          }, 400)
        }}
      >
        Save
      </Button>
      <Button onClick={onOpen} variant="outline">
        Open stack
      </Button>
      <Button
        onClick={() => toast.push({ title: 'Delete?', status: 'warning' })}
        tone="danger"
        variant="ghost"
      >
        Danger ghost
      </Button>
      </Stack>
    </Card>
  )
}

function Detail() {
  return <Card>Pushed screen. Back pops this tab stack.</Card>
}

function Inbox() {
  return <Card>Switching tabs does not push.</Card>
}

// templates/external-vite-vue/src/App.vue
<script setup lang="ts">
import {
  AppShell,
  Card,
  Navigation,
  NavigationBar,
  ThemeProvider,
  ToastProvider,
  useTabStacks,
} from '@chameleon-ui/vue'
import Home from './Home.vue'

const tabs = [
  { value: 'home', title: 'Home' },
  { value: 'inbox', title: 'Inbox' },
]

const stacks = useTabStacks(tabs)
const navItems = tabs.map((item) => ({ value: item.value, label: item.title }))
</script>

<template>
  <ThemeProvider theme="line" locale="zh-CN">
    <ToastProvider>
      <AppShell>
        <template #header>
          <NavigationBar
            :title="stacks.current.title"
            :back-label="stacks.previous?.title"
            :on-back="stacks.canPop ? stacks.pop : undefined"
          />
        </template>
        <template #navigation>
          <Navigation
            label="Main"
            :items="navItems"
            :active-value="stacks.tab"
            @select="stacks.selectTab"
          />
        </template>
        <Card v-if="stacks.current.id === 'detail'">Pushed screen. Back pops this tab stack.</Card>
        <Card v-else-if="stacks.tab === 'inbox'">Switching tabs does not push.</Card>
        <Home v-else @open="stacks.push({ id: 'detail', title: 'Detail' })" />
      </AppShell>
    </ToastProvider>
  </ThemeProvider>
</template>
