// packages/components-react/src/tab-bar/TabBar.tsx
import { TabsPrimitive } from '@chameleon-ui/primitives'
import type { ReactNode } from 'react'
import './styles.css'

export interface TabBarItem {
  value: string
  label: ReactNode
}

export interface TabBarProps {
  /** Accessible name of the navigation landmark. */
  label: string
  items: TabBarItem[]
  defaultValue?: string
  value?: string
  onChange?: (value: string) => void
  className?: string
}

export function TabBar({ label, items, defaultValue, value, onChange, className }: TabBarProps) {
  const classes = ['cu-tab-bar', className].filter(Boolean).join(' ')
  const active = value ?? defaultValue ?? items[0]?.value ?? 'default'

  return (
    <TabsPrimitive.Root
      className={classes}
      data-ai-role="tab-bar"
      data-ai-intent="navigate-sections"
      data-ai-state={active}
      defaultValue={defaultValue ?? items[0]?.value}
      value={value}
      onValueChange={(details) => onChange?.(details.value)}
    >
      <TabsPrimitive.List className="cu-tab-bar__list" aria-label={label}>
        {items.map((item) => (
          <TabsPrimitive.Trigger key={item.value} className="cu-tab-bar__item" value={item.value}>
            <span className="cu-tab-bar__label">{item.label}</span>
          </TabsPrimitive.Trigger>
        ))}
      </TabsPrimitive.List>
    </TabsPrimitive.Root>
  )
}

// chameleon-ui/packages/components-vue/src/tab-bar/TabBar.vue
<script lang="ts">
export interface TabBarItem {
  value: string
  label: string
}

export interface TabBarProps {
  label: string
  items: TabBarItem[]
  defaultValue?: string
  value?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { TabsPrimitive } from '@chameleon-ui/primitives-vue'

const props = defineProps<TabBarProps>()
const emit = defineEmits<{ change: [value: string] }>()
const classes = computed(() => ['cu-tab-bar', props.class].filter(Boolean).join(' '))
const active = computed(() => props.value ?? props.defaultValue ?? props.items[0]?.value ?? 'default')

function onValueChange(details: { value: string }) {
  emit('change', details.value)
}
</script>

<template>
  <TabsPrimitive.Root
    :class="classes"
    data-ai-role="tab-bar"
    data-ai-intent="navigate-sections"
    :data-ai-state="active"
    :default-value="defaultValue ?? items[0]?.value"
    :model-value="value"
    @value-change="onValueChange"
  >
    <TabsPrimitive.List class="cu-tab-bar__list" :aria-label="label">
      <TabsPrimitive.Trigger v-for="item in items" :key="item.value" class="cu-tab-bar__item" :value="item.value">
        <span class="cu-tab-bar__label">{{ item.label }}</span>
      </TabsPrimitive.Trigger>
    </TabsPrimitive.List>
  </TabsPrimitive.Root>
</template>

<style scoped src="./styles.css"></style>
