// packages/components-react/src/scroll-pane/ScrollPane.tsx
import type { CSSProperties, ReactNode } from 'react'
import './styles.css'

export type ScrollPaneOrientation = 'vertical' | 'horizontal' | 'both'

export interface ScrollPaneProps {
  children: ReactNode
  orientation?: ScrollPaneOrientation
  overscrollBehavior?: CSSProperties['overscrollBehavior']
  className?: string
}

export function ScrollPane({
  children,
  orientation = 'vertical',
  overscrollBehavior = 'contain',
  className,
}: ScrollPaneProps) {
  const classes = ['cu-scroll-pane', `cu-scroll-pane--${orientation}`, className]
    .filter(Boolean)
    .join(' ')
  return (
    <div
      className={classes}
      data-ai-role="scroll-pane"
      data-ai-intent="scroll-region"
      data-ai-state="default"
      style={{ overscrollBehavior }}
    >
      {children}
    </div>
  )
}

// packages/components-vue/src/scroll-pane/ScrollPane.vue
<script lang="ts">
export type ScrollPaneOrientation = 'vertical' | 'horizontal' | 'both'

export interface ScrollPaneProps {
  orientation?: ScrollPaneOrientation
  overscrollBehavior?: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<ScrollPaneProps>(), {
  orientation: 'vertical',
  overscrollBehavior: 'contain',
})

const classes = computed(() =>
  ['cu-scroll-pane', `cu-scroll-pane--${props.orientation}`, props.class].filter(Boolean).join(' '),
)
</script>

<template>
  <div
    :class="classes"
    data-ai-role="scroll-pane"
    data-ai-intent="scroll-region"
    data-ai-state="default"
    :style="{ overscrollBehavior }"
  >
    <slot />
  </div>
</template>

<style src="./styles.css"></style>
