// packages/components/src/stack/Stack.tsx
import type { ReactNode } from 'react'
import './styles.css'

export type StackDirection = 'row' | 'column'
export type StackGap = '0' | '1' | '2' | '3' | '4' | '5' | '6'
export type StackAlignment = 'start' | 'center' | 'end' | 'stretch'
export type StackJustify = 'start' | 'center' | 'end' | 'between'

export interface StackProps {
  direction?: StackDirection
  gap?: StackGap
  align?: StackAlignment
  justify?: StackJustify
  children: ReactNode
  className?: string
}

export function Stack({
  direction = 'column',
  gap = '2',
  align = 'stretch',
  justify = 'start',
  children,
  className,
}: StackProps) {
  const classes = ['cu-stack', `cu-stack--${direction}`, `cu-stack--gap-${gap}`, className]
    .filter(Boolean)
    .join(' ')

  return (
    <div
      className={classes}
      data-ai-role="stack" data-ai-intent="layout-flow"
      data-ai-state="default"
      data-direction={direction}
      data-gap={gap}
      data-align={align}
      data-justify={justify}
    >
      {children}
    </div>
  )
}

// chameleon-ui/packages/components-vue/src/stack/Stack.vue
<script lang="ts">
export type StackDirection = 'row' | 'column'
export type StackGap = '0' | '1' | '2' | '3' | '4' | '5' | '6'
export type StackAlignment = 'start' | 'center' | 'end' | 'stretch'
export type StackJustify = 'start' | 'center' | 'end' | 'between'

export interface StackProps {
  direction?: StackDirection
  gap?: StackGap
  align?: StackAlignment
  justify?: StackJustify
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<StackProps>(), {
  direction: 'column',
  gap: '2',
  align: 'stretch',
  justify: 'start',
})

const classes = computed(() =>
  ['cu-stack', `cu-stack--${props.direction}`, `cu-stack--gap-${props.gap}`, props.class]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div
    :class="classes"
    data-ai-role="stack"
    data-ai-intent="layout-flow"
    data-ai-state="default"
    :data-direction="direction"
    :data-gap="gap"
    :data-align="align"
    :data-justify="justify"
  >
    <slot />
  </div>
</template>

<style scoped src="./styles.css"></style>
