// chameleon-ui/packages/components/src/alert/Alert.tsx
import type { ReactNode } from 'react'
import './styles.css'

export type AlertStatus = 'info' | 'success' | 'warning' | 'error'

export interface AlertProps {
  status?: AlertStatus
  title: string
  description: ReactNode
  className?: string
}

export function Alert({ status = 'info', title, description, className }: AlertProps) {
  const classes = ['cu-alert', `cu-alert--${status}`, className].filter(Boolean).join(' ')

  return (
    <div
      aria-label={title}
      className={classes}
      data-ai-role="alert" data-ai-intent="notify-status"
      data-ai-state={status}
      role={status === 'error' ? 'alert' : 'status'}
      aria-live={status === 'error' ? 'assertive' : 'polite'}
    >
      <div className="cu-alert__title">{title}</div>
      <div className="cu-alert__description">{description}</div>
    </div>
  )
}

// chameleon-ui/packages/components-vue/src/alert/Alert.vue
<script lang="ts">
export type AlertStatus = 'info' | 'success' | 'warning' | 'error'

export interface AlertProps {
  status?: AlertStatus
  title: string
  description: string
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<AlertProps>(), {
  status: 'info',
})

const classes = computed(() =>
  ['cu-alert', `cu-alert--${props.status}`, props.class].filter(Boolean).join(' '),
)
const role = computed(() => (props.status === 'error' ? 'alert' : 'status'))
const live = computed(() => (props.status === 'error' ? 'assertive' : 'polite'))
</script>

<template>
  <div
    :aria-label="title"
    :class="classes"
    data-ai-role="alert"
    data-ai-intent="notify-status"
    :data-ai-state="status"
    :role="role"
    :aria-live="live"
  >
    <div class="cu-alert__title">{{ title }}</div>
    <div class="cu-alert__description">{{ description }}</div>
  </div>
</template>

<style scoped src="./styles.css"></style>
