// chameleon-ui/packages/components/src/list/List.tsx
import './styles.css'

export interface ListProps {
  items: string[]
  variant?: 'unordered' | 'ordered' | 'none'
  className?: string
}

export function List({ items, variant = 'unordered', className }: ListProps) {
  const classes = ['cu-list', 'cu-list--' + variant, className].filter(Boolean).join(' ')
  const Tag = variant === 'ordered' ? 'ol' : 'ul'
  return (
    <Tag className={classes} data-ai-role="list" data-ai-intent="enumerate-items" data-ai-state={variant}>
      {items.map((item, index) => <li className="cu-list__item" key={index}>{item}</li>)}
    </Tag>
  )
}

// packages/components-vue/src/list/List.vue
<script lang="ts">
export interface ListProps {
  items: string[]
  variant?: 'unordered' | 'ordered' | 'none'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<ListProps>(), {
  variant: 'unordered'
})
const classes = computed(() => ["cu-list", 'cu-list--' + props.variant, props.class].filter(Boolean).join(' '))
</script>

<template>
  <ol v-if="variant === 'ordered'" :class="classes" data-ai-role="list" data-ai-intent="enumerate-items" :data-ai-state="variant">
    <li v-for="(item, index) in items" :key="index" class="cu-list__item">{{ item }}</li>
  </ol>
  <ul v-else :class="classes" data-ai-role="list" data-ai-intent="enumerate-items" :data-ai-state="variant">
    <li v-for="(item, index) in items" :key="index" class="cu-list__item">{{ item }}</li>
  </ul>
</template>

<style scoped src="./styles.css"></style>
