// packages/components-vue/src/badge/Badge.vue
<script lang="ts">
export interface BadgeProps {
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger'
  size?: 'sm' | 'md'
  class?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<BadgeProps>(), {
  variant: 'default',
  size: 'md',
})

const classes = computed(() =>
  ['cu-badge', `cu-badge--${props.variant}`, `cu-badge--${props.size}`, props.class]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <span :class="classes" data-ai-role="badge" data-ai-intent="flag-status" :data-ai-state="variant">
    <slot />
  </span>
</template>

<style scoped src="./styles.css"></style>

// chameleon-ui/packages/components/src/badge/Badge.tsx
import type { ReactNode } from 'react'
import './styles.css'

export interface BadgeProps {
  children: ReactNode
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger'
  size?: 'sm' | 'md'
  className?: string
}

export function Badge({ children, variant = 'default', size = 'md', className }: BadgeProps) {
  const classes = ['cu-badge', 'cu-badge--' + variant, 'cu-badge--' + size, className].filter(Boolean).join(' ')
  return <span className={classes} data-ai-role="badge" data-ai-intent="flag-status" data-ai-state={variant}>{children}</span>
}
